### ISSUE TITLE
Uncaught TypeError: Cannot read property 'componentWillReceiveProps' of null

### ISSUE THREAD

**Issue by IvanYurchenko** [facebook/nuclide#461] opened 2016-04-17 15:26 UTC
Steps to reproduce:
1. Press 'Show only diagnostics for current file' button.
2. Get an exception.

Stack trace:
/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:457
Hide Stack Trace
TypeError: Cannot read property 'componentWillReceiveProps' of null
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:457:15)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:417:23)
  at Object.ReactReconciler.performUpdateIfNecessary (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:102:22)
  at runBatchedUpdates (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:129:21)
  at ReactReconcileTransaction.Mixin.perform (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at ReactUpdatesFlushTransaction.assign.perform (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:86:38)
  at Object.flushBatchedUpdates (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:147:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:202:25)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:149:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
  at Object.batchedUpdates (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:94:20)
  at ReactEventListener.dispatchEvent (/Users/ivanyurchenko/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:204:20)

**Comment by zertosh** [comment] 2016-04-18 06:47
I can't repro. What version of Atom/Nuclide are you running? Did you have any files open?

**Comment by LazerMax** [comment] 2016-04-21 10:30
I was using Atom 1.7.1 and Nuclide 0.130.0. I've had one js file opened that is the React Native's index.io.is.

Actually, I've just upgraded the Nuclide to the 0.130.1 version and the bug isn't reproducable now. But I still don't see any errors, could you help me with this? [https://i.gyazo.com/f3b95d542a4682b14860a8c5972c240a.png](screen)

Also the stacktrace of this error was too long for the GitHub so when I clicked the Post button it turned out to be a Too-long-querystring error on the GutHub side and I should have copied it manually. Perhaps you could check the stack trace for corresponding the GitHub's max possible length.

**Comment by zertosh** [comment] 2016-06-06 20:45
Closing since the issue was fixed by an update.

**Closed by zertosh** 2016-06-06 20:45 UTC
