### ISSUE TITLE
Uncaught Error: Cannot find module '../../commons-node/fb-node-run.sh'

### ISSUE THREAD

**Issue by rahulgurujala** [facebook/nuclide#1418] opened 2017-12-21 10:04 UTC
### Issue and Steps to Reproduce
C:\Users\rahulgurujala\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:93

Error: Cannot find module '../../commons-node/fb-node-run.sh'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\module-cache.js:354:58)
    at Function.require.resolve (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\native-compile-cache.js:69:35)
    at createLocalRpcClient (C:\Users\rahulgurujala\.atom\packages\nuclide\pkg\nuclide-remote-connection\lib\service-manager.js:99:29)
    at getlocalService (C:\Users\rahulgurujala\.atom\packages\nuclide\pkg\nuclide-remote-connection\lib\service-manager.js:123:24)
    at getServiceByConnection (C:\Users\rahulgurujala\.atom\packages\nuclide\pkg\nuclide-remote-connection\lib\service-manager.js:167:12)
    at ConnectionCache.<anonymous> (C:\Users\rahulgurujala\.atom\packages\nuclide\pkg\nuclide-flow\lib\main.js:43:114)
    at Generator.next (<anonymous>)
    at step (C:\Users\rahulgurujala\.atom\packages\nuclide\node_modules\async-to-generator\async-to-generator.js:11:30)
    at C:\Users\rahulgurujala\.atom\packages\nuclide\node_modules\async-to-generator\async-to-generator.js:29:7
    at ConnectionCache.<anonymous> (C:\Users\rahulgurujala\.atom\packages\nuclide\node_modules\async-to-generator\async-to-generator.js:8:12)
    at ConnectionCache.connectionToFlowService [as _factory] (C:\Users\rahulgurujala\.atom\packages\nuclide\pkg\nuclide-flow\lib\main.js:64:18)
    at ConnectionCache.get (C:\Users\rahulgurujala\.atom\packages\nuclide\modules\nuclide-commons\cache.js:26:29)
    at ConnectionCache (C:\Users\rahulgurujala\.atom\packages\nuclide\pkg\nuclide-remote-connection\lib\ConnectionCache.js:54:12)
    at Object.<anonymous> (C:\Users\rahulgurujala\.atom\packages\nuclide\pkg\nuclide-flow\lib\main.js:13:25)
    at Generator.next (<anonymous>)
    at step (C:\Users\rahulgurujala\.atom\packages\nuclide\node_modules\async-to-generator\async-to-generator.js:11:30)
    at C:\Users\rahulgurujala\.atom\packages\nuclide\node_modules\async-to-generator\async-to-generator.js:29:7
    at Object.<anonymous> (C:\Users\rahulgurujala\.atom\packages\nuclide\node_modules\async-to-generator\async-to-generator.js:8:12)
    at Object.activate (C:\Users\rahulgurujala\.atom\packages\nuclide\pkg\nuclide-flow\lib\main.js:37:17)
    at Package.module.exports.Package.activateNow (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\package.js:255:25)
    at C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\package.js:1068:34
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at PackageManager.triggerActivationHook (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\package-manager.js:732:40)
    at Workspace.handleGrammarUsed (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\workspace.js:1401:40)
    at TextEditor.observeGrammar (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\text-editor.js:727:11)
    at C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\workspace.js:579:202
    at C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\workspace.js:584:19
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at PaneContainer.didAddPaneItem (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\pane-container.js:270:24)
    at Pane.addItem (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\pane.js:632:48)
    at Pane.activateItem (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\pane.js:574:18)
    at Workspace.<anonymous> (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\workspace.js:1175:20)
    at Generator.next (<anonymous>)
    at step (C:\Users\rahulgurujala\AppData\Local\atom\app-1.23.1\resources\app\src\workspace.js:11:279)

### Expected Behavior
Uncaught Error: Cannot find module 

### Actual Behavior
Crash

### Versions
* Atom:v1.23.1x64
* Nuclide:0.2720
* Client OS:Windows 10 64bit
* Server OS (optional):Windows 10 64bit

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by a7madgamal** [comment] 2017-12-21 11:41
this looks bad :(
I tried deactivating, reinstalling the package, restarting atom many times. same error
Looking at the devtools it looks like it might be affecting many things

> /Users/miamed/.atom/packages/nuclide/pkg/nuclide-logging/lib/consoleAppender.js:52 [2017-12-21T11:31:15.676Z] [ERROR] nuclide-buck -  Cannot find module '../../commons-node/fb-node-run.sh'
> Error: Cannot find module '../../commons-node/fb-node-run.sh'
>     at Module._resolveFilename (module.js:470:15)
>     at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
>     at Function.get_Module._resolveFilename 


> /Users/miamed/.atom/packages/nuclide/pkg/nuclide-logging/lib/consoleAppender.js:52 [2017-12-21T11:31:15.684Z] [ERROR] nuclide-language-service - Error: languageService, jsimports.observe-diagnostics Error: Cannot find module '../../commons-node/fb-node-run.sh'
> /Users/miamed/.atom/packages/nuclide/pkg/nuclide-logging/lib/consoleAppender.js:52 [2017-12-21T11:31:16.896Z] [WARN] nuclide-quick-open - isEligibleForDirectory failed for directory provider CodeSearchProvider Cannot find module '../../commons-node/fb-node-run.sh'
> 



> /Users/miamed/.atom/packages/nuclide/pkg/nuclide-logging/lib/consoleAppender.js:52 [2017-12-21T11:31:16.899Z] [WARN] nuclide-quick-open - isEligibleForDirectory failed for directory provider CodeSearchProvider Cannot find module '../../commons-node/fb-node-run.sh'
> Error: Cannot find module '../../commons-node/fb-node-run.sh'
>     at Module._resolveFilename (module.js:470:15)
>     at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
> 


> Enabling timed out

and many more

**Comment by albinhubsch** [comment] 2017-12-21 14:58
Also seen on Mac OS X, Sierra.

**Comment by zinoviev** [comment] 2017-12-21 15:57
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.272.0


### Stack Trace

Uncaught Error: Cannot find module '../../commons-node/fb-node-run.sh'

```
At /Users/zigi/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:93

Error: Cannot find module '../../commons-node/fb-node-run.sh'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Function.require.resolve (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:69:35)
    at createLocalRpcClient (/packages/nuclide/pkg/nuclide-remote-connection/lib/service-manager.js:99:29)
    at getlocalService (/packages/nuclide/pkg/nuclide-remote-connection/lib/service-manager.js:123:24)
    at getServiceByConnection (/packages/nuclide/pkg/nuclide-remote-connection/lib/service-manager.js:167:12)
    at /packages/nuclide/pkg/nuclide-flow/lib/main.js:43:114)
    at Generator.next (<anonymous>)
    at step (/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:29:7
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12)
    at /packages/nuclide/pkg/nuclide-flow/lib/main.js:64:18)
    at ConnectionCache.get (/packages/nuclide/modules/nuclide-commons/cache.js:26:29)
    at ConnectionCache (/packages/nuclide/pkg/nuclide-remote-connection/lib/ConnectionCache.js:54:12)
    at /packages/nuclide/pkg/nuclide-flow/lib/main.js:13:25)
    at Generator.next (<anonymous>)
    at step (/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:29:7
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12)
    at Object.activate (/packages/nuclide/pkg/nuclide-flow/lib/main.js:37:17)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:255:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:1068:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:717:40)
    at Promise.all.then (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:650:18)
```

### Commands

```
     -0:20.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-ide-ui 0.7.0 
atom-material-ui 2.0.6 
atom-typescript 11.0.10 
busy-signal 1.4.3 
docblockr 0.13.4 
editorconfig 2.2.2 
file-icons 2.1.15 
git-blame 1.4.0 
git-plus 7.10.0 
glam-atom 2.0.0 
intentions 1.1.5 
language-babel 2.81.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
nuclide 0.272.0 
prettier-atom 0.43.1 
pure-syntax 0.3.0 
react-native-snippets 0.3.0 
react-snippets 1.0.1 
redux-devtools 0.5.1 
seti-ui 1.9.0 
```

**Comment by isaacwhanson** [comment] 2017-12-21 16:28
**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: "Arch Linux"
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.272.0

### Stack Trace

Uncaught Error: Cannot find module '../../commons-node/fb-node-run.sh'
...

**Comment by ibio** [comment] 2017-12-21 18:42
[Enter steps to reproduce:]

1. upgrade to the latest nuclide
2. restart

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.272.0


### Stack Trace

Uncaught Error: Cannot find module '../../commons-node/fb-node-run.sh'

```
At /Users/ytan/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:93

Error: Cannot find module '../../commons-node/fb-node-run.sh'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Function.require.resolve (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:69:35)
    at createLocalRpcClient (/packages/nuclide/pkg/nuclide-remote-connection/lib/service-manager.js:99:29)
    at getlocalService (/packages/nuclide/pkg/nuclide-remote-connection/lib/service-manager.js:123:24)
    at getServiceByConnection (/packages/nuclide/pkg/nuclide-remote-connection/lib/service-manager.js:167:12)
    at /packages/nuclide/pkg/nuclide-open-files/lib/NotifiersByConnection.js:78:99)
    at /packages/nuclide/pkg/nuclide-open-files/lib/NotifiersByConnection.js:100:27)
    at ConnectionCache.get (/packages/nuclide/modules/nuclide-commons/cache.js:26:29)
    at ConnectionCache (/packages/nuclide/pkg/nuclide-remote-connection/lib/ConnectionCache.js:54:12)
    at /packages/nuclide/pkg/nuclide-open-files/lib/NotifiersByConnection.js:99:23)
    at /packages/nuclide/pkg/nuclide-open-files/lib/main.js:96:23)
    at /packages/nuclide/pkg/nuclide-open-files/lib/main.js:150:18)
    at /packages/nuclide/pkg/nuclide-open-files/lib/main.js:174:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _load_nuclideOpenFiles (/packages/nuclide/pkg/nuclide-language-service/lib/CodeActionProvider.js:19:30)
    at /packages/nuclide/pkg/nuclide-language-service/lib/CodeActionProvider.js:49:59
    at Generator.next (<anonymous>)
    at step (/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:29:7
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12
    at trackTiming (/packages/nuclide/pkg/nuclide-analytics/lib/main.js:151:20)
    at CodeActionProvider.getCodeActions (/packages/nuclide/pkg/nuclide-language-service/lib/CodeActionProvider.js:48:76)
    at /packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-code-actions/lib/CodeActionManager.js:127:42
    at Generator.next (<anonymous>)
    at step (/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:29:7
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12
    at CodeActionManager._genAllCodeActions (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-code-actions/lib/CodeActionManager.js:130:7)
    at /packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-code-actions/lib/CodeActionManager.js:174:62)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:261:315)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:262:433)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:136:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:183:159)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:262:433)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:105:241)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at b.observe (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:99:99)
    at a.dispatch (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:174:524)
    at a._execute (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:118:206)
    at a.execute (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:118:27)
    at a.flush (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:119:368)
```

### Commands

```
     -0:31.8.0 nuclide-file-tree:toggle (div.panels-item)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
busy-signal 1.4.3 
emmet 2.4.3 
git-blame 1.4.0 
git-plus 7.10.0 
intentions 1.1.5 
language-markdown 0.25.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
nuclide 0.272.0 
prettier-atom 0.43.1 
react 0.17.0 
```

**Comment by albinhubsch** [comment] 2017-12-21 19:14
Duplicate of #1412

**Comment by hansonw** [comment] 2017-12-21 19:48
Shit, sorry about this guys - I'll push the fix shortly. In the meantime there are two workarounds:

1) Downgrade to v0.271.0
2) In console, run `atom.config.set('nuclide.useLocalRpc', false)` and reload Atom

v273 will have the fix.

**Comment by hansonw** [comment] 2017-12-21 19:49
I've unpublished 0.272.0 for now.

**Comment by hansonw** [comment] 2017-12-21 20:58
v273 is out with the fix, apologies for this one!

**Closed by hansonw** 2017-12-21 20:58 UTC

**Comment by a7madgamal** [comment] 2017-12-22 13:24
@hansonw thanks for the quick fix!
