### ISSUE TITLE
Uncaught Error: Diff view only supports `Mercurial` repositories, but found `no repository` at pa...

### ISSUE THREAD

**Issue by ah-kevin** [facebook/nuclide#555] opened 2016-06-20 06:23 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.141.0

### Stack Trace

Uncaught Error: Diff view only supports `Mercurial` repositories, but found `no repository` at path: `/Applications/Atom.app/Contents/Resources`

```
At /Users/dg_lennon/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:195

Error: Diff view only supports `Mercurial` repositories, but found `no repository` at path: `/Applications/Atom.app/Contents/Resources`
  at hgRepositoryForPath (/Users/dg_lennon/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:195:11)
  at DiffViewModel._getRepositoryStackForPath (/Users/dg_lennon/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:720:26)
  at DiffViewModel._findFilePathToDiffInDirectory (/Users/dg_lennon/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:509:34)
  at DiffViewModel.diffEntity (/Users/dg_lennon/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:531:25)
  at activateDiffPath (/Users/dg_lennon/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:164:17)
  at createView (/Users/dg_lennon/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:120:3)
  at /Users/dg_lennon/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:342:16
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:489:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:424:19)
  at Workspace.module.exports.Workspace.reopenItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:629:21)
  at atom-workspace.commandRegistry.add.pane:reopen-closed-item (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:208:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
  at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)

```

### Commands

```
     -0:49.6.0 nuclide-diff-view:open (atom-text-editor.editor)
     -0:34.1.0 nuclide-debugger:toggle (atom-text-editor.editor)
  2x -0:33.2.0 nuclide-diagnostics-ui:toggle-table (atom-text-editor.editor)
     -0:00.7.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-blame-provider-hg": {},
    "nuclide-file-tree": {},
    "nuclide-flow": {},
    "nuclide-home": {
      "showHome": false
    },
    "use": {}
  }
}
```

### Installed Packages

```coffee
# User
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.28.0
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
nuclide, v0.141.0
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by nmote** [comment] 2016-06-20 23:55
Please include steps to reproduce. In particular, if you are trying to use diff view on anything besides a Mercurial repository, this is expected behavior as noted in the error message.

**Comment by mostafaeweda** [comment] 2016-09-12 20:58
duplicate of #555

**Closed by mostafaeweda** 2016-09-12 20:58 UTC
