### ISSUE TITLE
nuclide not instlling (Installing “nuclide@0.311.0” failed)

### ISSUE THREAD

**Issue by amnilesh** [facebook/nuclide#1548] opened 2018-06-08 15:48 UTC
Installing “nuclide@0.311.0” failed.Hide output…

> runas@3.1.1 install C:\Users\Neil\AppData\Local\Temp\apm-install-dir-11858-9724-oa38np.zlts2zw7b9\node_modules\nuclide\node_modules\runas
> node-gyp rebuild

C:\Users\Neil\AppData\Local\Temp\apm-install-dir-11858-9724-oa38np.zlts2zw7b9\node_modules\nuclide\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\Neil\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Neil\AppData\Local\atom\app-1.27.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
C:\Users\Neil\AppData\Local\Temp\apm-install-dir-11858-9724-oa38np.zlts2zw7b9
`-- (empty)

npm WARN excluding symbolic link pkg\nuclide-fs-atom\__mocks__\fixtures -> ../../nuclide-fs/spec/fixtures
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\Directory\LinkDotDotSlashTextFile.txt -> ../TextFile.txt
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkDirectory -> Directory
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkDirectorySlashTextFile.txt -> Directory/TextFile.txt
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkLinkDirectory -> LinkDirectory
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkLinkDirectorySlashTextFile.txt -> LinkDirectorySlashTextFile.txt
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN excluding symbolic link pkg\nuclide-fs-atom\__mocks__\fixtures -> ../../nuclide-fs/spec/fixtures
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\Directory\LinkDotDotSlashTextFile.txt -> ../TextFile.txt
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkDirectory -> Directory
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkDirectorySlashTextFile.txt -> Directory/TextFile.txt
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkLinkDirectory -> LinkDirectory
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkLinkDirectorySlashTextFile.txt -> LinkDirectorySlashTextFile.txt
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Neil\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Neil\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Neil\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Neil\AppData\Local\Temp\apm-install-dir-11858-9724-oa38np.zlts2zw7b9\node_modules\nuclide\node_modules\runas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Neil\AppData\Local\Temp\apm-install-dir-11858-9724-oa38np.zlts2zw7b9\package.json'
npm WARN graphql-language-service-utils@1.1.0 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN graphql-language-service@1.1.2 requires a peer of graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN relay-runtime@1.6.0 requires a peer of relay-compiler@1.6.0 but none was installed.
npm WARN graphql-language-service-types@1.2.1 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN apm-install-dir-11858-9724-oa38np.zlts2zw7b9 No description
npm WARN apm-install-dir-11858-9724-oa38np.zlts2zw7b9 No repository field.
npm WARN apm-install-dir-11858-9724-oa38np.zlts2zw7b9 No README data
npm WARN apm-install-dir-11858-9724-oa38np.zlts2zw7b9 No license field.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\Neil\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Neil\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Neil\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Neil\\.atom\\.apmrc" "install" "C:\\Users\\Neil\\AppData\\Local\\Temp\\d-11858-9724-154nlz4.xqspaxlxr\\package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Neil\AppData\Local\Temp\apm-install-dir-11858-9724-oa38np.zlts2zw7b9\npm-debug.log
npm ERR! code 1 how to reproduce it (include screenshots and/or any console messages).

### Versions
* Atom: 1.27.2
* Nuclide : 0.311.0
* Client OS : windows 10
* node-js - 8.11.2 LTS (  version - 10.4.0   also tried latest version )
python - 2.7.15
Latest Features

Community Packages (16) 
├── atom-beautify@0.32.5
├── atom-ide-debugger-react-native@0.7.1
├── atom-react-native-style@0.2.0
├── atom-ternjs@0.18.3
├── atom-wrap-in-tag@0.6.0
├── autoclose-html@0.23.0
├── autocomplete-modules@2.0.0
├── color-picker@2.3.0
├── emmet@2.4.3
├── file-icons@2.1.21
├── highlight-selected@0.13.1
├── language-babel@2.85.0
├── platformio-ide-debugger@1.2.6
├── sort-lines@0.18.0
├── tool-bar@1.1.7
└── tree-view-copy-relative-path@1.2.0

**Comment by semmypurewal** [comment] 2018-06-08 17:55
Sorry you're having trouble! We're aware of this issue and have a fix for it. Unfortunately it won't be out until Monday or Tuesday at the earliest. In the meantime, try installing 0.310.0 which shouldn't have this problem.

(This is a duplicate of #1547 and #1546.)

**Closed by semmypurewal** 2018-06-08 17:55 UTC

**Comment by dangell7** [comment] 2018-06-11 02:11
Are we still on for monday or tuesday? I tried installing an earlier version and now I have a timeout error. If your "stable" version is 311 then 311 is what we shall use. Please update us on the status of the working "stable" 311 version. ;)
