### ISSUE TITLE
Cannot react native start package!

### ISSUE THREAD

**Issue by Liuhuan247** [facebook/nuclide#1373] opened 2017-11-09 06:55 UTC
### Issue and Steps to Reproduce
I update nuclide and atom.Then react native start package in command palette.

An unexpected error occurred while running the React Native Packager process:
ENOTDIR: not a directory, stat '/Users/liuhuan/Desktop/Navigator/reactNavigation/package.json/package.json'
![1510210455031](https://user-images.githubusercontent.com/8871075/32592256-8a04008a-c4e8-11e7-8d9d-b189e8cf54b5.jpg)

### Versions
* Atom:1.22.0
* Nuclide:0.266.0
* Client OS:macOS 10.12.6
* Server OS (optional):

**Comment by Liuhuan247** [comment] 2017-11-09 06:56
How to solve this?

**Comment by hansonw** [comment] 2017-11-09 07:18
Dupe of #1372, I'll update that one

**Closed by hansonw** 2017-11-09 07:18 UTC
