### ISSUE TITLE
can we control the autocomplete priority in flow?

### ISSUE THREAD

**Issue by Mohamed-Abo-El-Soud** [facebook/nuclide#766] opened 2016-10-06 03:55 UTC
### Issue and Steps to Reproduce

It seems that there is no way to control the priority of the autocomplete suggestions offered by Flow. It seems that it takes the highest priority over all other suggestions. For example, i am used to typing `log` and the first auto complete suggestion would give me `console.log(' ')`. But when i enable nuclide, then i type `log`, most of the top suggestions are the variables in the file (likely provided by flow). So unfortunately, I can't press tab anymore in order to auto complete into `console.log`. Is there a way I can control this behaviour? This behaviour immediately disappears when I disable nuclide.

I like using flow, but I just don't want it taking the highest priority in autocomplete.
### Expected Behavior

typing `log` should offer me snippets first then suggestions by flow
### Actual Behavior

typing `log` offers suggestions by flow, then snippets at the very bottom.
### Versions
- Atom: 1.10.2
- Nuclide: 0.171.0
- Client OS: OSX El Capitan
- Server OS (optional):
### Additional Details
- Installed packages (`apm ls --installed`):

├── an-old-hope-syntax@0.5.0
├── atom-beautify
├── atom-ctags@5.0.0
├── atom-live-server@1.2.5
├── atom-material-syntax@0.4.6
├── atom-material-syntax-light@0.4.5
├── atom-material-ui@1.3.6
├── atom-react-native-autocomplete@0.0.27
├── atom-terminal@0.8.0
├── atom-ternjs@0.15.0
├── atom-typescript@8.11.0
├── atomic-chrome@0.3.0
├── autocomplete@0.47.0
├── autocomplete-java@1.2.5
├── autocomplete-js-import@1.2.1
├── autocomplete-modules@1.6.7
├── autocomplete-paths@1.0.2
├── autocomplete-python@1.8.6
├── build-gulp@0.11.0
├── busy@0.6.0
├── color-picker@2.2.2
├── docblockr@0.8.4
├── emmet@2.4.3
├── es6-javascript@1.0.0
├── expand-region@0.2.4
├── file-icons@1.7.19
├── flow-ide@1.1.6
├── genesis-ui@0.5.0
├── git-diff-details@1.3.0
├── git-plus@5.16.2
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── hyperclick@0.0.39
├── js-hyperclick@1.4.2
├── js-refactor@0.7.3
├── kyaho-dark-syntax@1.0.0
├── kyaho-syntax@0.3.0
├── language-babel@2.36.0
├── language-gradle@0.0.3
├── language-ini@1.16.0
├── language-javascript-better@1.7.1
├── language-javascript-jsx@0.3.7
├── language-mongodb@0.3.1
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.16
├── linter-eslint@7.3.2
├── linter-jshint@3.0.0
├── merge-conflicts@1.4.4
├── minimap@4.24.7
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.1
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.4.0
├── minimap-linter@1.6.0
├── minimap-pigments@0.2.1
├── minimap-selection@4.4.0
├── nucleus-dark-ui@0.9.3
├── nuclide@0.171.0
├── pigments@0.34.0
├── polymer-snippets@3.2.1
├── react@0.16.0
├── react-es6-snippets@0.3.0
├── react-native-snippets@0.3.0
├── react-snippets@0.5.0
├── refactor@0.9.2
├── remote-atom@1.3.9
├── run-in-atom@1.0.5
├── save-session@0.16.0
├── script@3.9.0
├── sort-lines@0.14.0
├── terminal-plus@0.14.5
├── todo-show@1.7.0
├── tool-bar@1.0.1
├── tool-bar-atom@1.6.3
└── vim-mode@0.65.1

└── (empty)

**Comment by nmote** [comment] 2016-10-06 18:57
There's currently no setting for it, but I think it would be reasonable to add one. Due to the way autocomplete-plus works, it would have to require a restart of Atom in order to apply. I would happily review a PR to add this.

**Comment by Mohamed-Abo-El-Soud** [comment] 2016-10-08 15:23
ok so i just found a temporary solution in @benogle 's suggestion:
https://github.com/atom/autocomplete-plus/issues/522#issuecomment-124597315

**Comment by alexfedoseev** [comment] 2016-11-11 09:23
https://github.com/facebook/nuclide/pull/877

**Comment by jgebhardt** [comment] 2017-01-12 06:02
Yep, this is a dupe of #877. Fixed in https://github.com/facebook/nuclide/commit/11a05fe4c2e1d2c7c1fe1e57709c3f2ba5482e02

**Closed by jgebhardt** 2017-01-12 06:02 UTC
Labels: help wanted
