### ISSUE TITLE
Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full er...

### ISSUE THREAD

**Issue by zurawiki** [facebook/nuclide#133] opened 2015-07-06 20:25 UTC
When editing react javascript files, this error keeps coming up

**Atom Version**: 1.0.12466783
**System**: Mac OS X 10.10.4
**Thrown From**: [hyperclick](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

```
At /Users/rmz/Tools/Nuclide/pkg/nuclide/hyperclick/node_modules/react-for-atom/node_modules/react/lib/invariant.js:49

Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (/Users/rmz/Tools/Nuclide/pkg/nuclide/hyperclick/node_modules/react-for-atom/node_modules/react/lib/invariant.js:35:15)
  at findDOMNode (/Users/rmz/Tools/Nuclide/pkg/nuclide/hyperclick/node_modules/react-for-atom/node_modules/react/lib/findDOMNode.js:60:7)
  at [object Object].ReactBrowserComponentMixin.getDOMNode (/Users/rmz/Tools/Nuclide/pkg/nuclide/hyperclick/node_modules/react-for-atom/node_modules/react/lib/ReactBrowserComponentMixin.js:25:12)
  at [object Object].close (/Users/rmz/Tools/Nuclide/pkg/nuclide/ssh-dialog/lib/ConnectionDialog.js:476:39)
  at Object.onError (/Users/rmz/Tools/Nuclide/pkg/nuclide/ssh-dialog/lib/ConnectionDialog.js:377:16)
  at Client.<anonymous> (/Users/rmz/Tools/Nuclide/pkg/nuclide/remote-connection/lib/SshHandshake.js:66:30)
  at emitOne (events.js:77:13)
  at Client.emit (events.js:166:7)
  at Socket.<anonymous> (/Users/rmz/Tools/Nuclide/pkg/nuclide/remote-connection/node_modules/ssh2/lib/client.js:215:10)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at net.js:438:14
  at process._tickCallback (node.js:357:13)

```

### Commands

```
  2x -4:11.2.0 core:delete (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -4:08.8.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:32.2.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:31.7.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:22.8.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:21 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -1:19.2.0 editor:indent-selected-rows (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:18.3.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:20.4.0 core:copy (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:18.5.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:18.3.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:14.4.0 core:cut (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  4x -0:13.4.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:11.1.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:09.6.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 10x -0:08.6.0 core:delete (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop",
      "tree-view"
    ],
    "themes": [
      "isotope-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
arcanist, v0.0.0
autocomplete-plus-clang, v0.0.0
buck, v0.0.0
debugger-hhvm, v0.0.0
debugger-lldb, v0.0.0
fb-analytics-client, v0.0.0
fb-diffs-and-tasks, v0.0.0
fb-file-a-bug, v0.0.0
fb-nuclide-installer, v0.0.0
fb-package-manager, v0.0.0
graphql, v0.0.0
haskell-grammar, v0.3.0
hyperclick, v0.0.0
isotope-ui, v2.5.0
language-javascript-jsx, v0.3.6
language-ocaml, v1.1.1
linter, v1.0.4
nuclide-blame-ui, v0.0.0
nuclide-code-format, v0.0.0
nuclide-debugger, v0.0.0
nuclide-debugger-node, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-file-creation, v0.0.0
nuclide-file-creation-ios, v0.0.0
nuclide-file-tree, v0.0.0
nuclide-file-watcher, v0.0.0
nuclide-flow, v0.0.0
nuclide-hack, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-installer, v0.0.0
nuclide-language-hack, v0.0.0
nuclide-log-viewer, v0.0.0
nuclide-logging-helper, v0.0.0
nuclide-objc, v0.0.0
nuclide-phabricator-comments, v0.0.0
nuclide-quick-open, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-tabs-per-branch, v0.0.0
nuclide-toolbar, v0.0.0
nuclide-type-hint, v0.0.0
react, v0.12.3
seti-syntax, v0.4.0
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by ssorallen** [comment] 2015-07-06 21:13
Have you been editing remote files?

This is the same stack trace as #98, and it looks like the root cause is in the ConnectionDialog. I'm going to close this as a duplicate.

**Closed by ssorallen** 2015-07-06 21:13 UTC
Labels: duplicate

**Comment by KurtRMueller** [comment] 2015-10-21 21:42
Came up with me and I'm not editing remote files.

**Comment by domarmstrong** [comment] 2015-11-24 14:55
:+1: was directed here from atom. no editing externally.

**Comment by Jeff-Coons** [comment] 2016-02-09 19:14
Keep running into this issue as well when editing local files

**Comment by peramsathyam** [comment] 2016-02-10 14:38
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (/Users/jpnath/.atom/packages/nuclide/node_modules/react/node_modules/fbjs/lib/invariant.js:35:15)
  at Object.ReactMount.findComponentRoot (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:764:478)
  at Object.ReactMount.findReactNodeByID (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:679:23)
  at Object.getNode (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:162:32)
  at Object.SimpleEventPlugin.didPutListener (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/SimpleEventPlugin.js:571:29)
  at Object.EventPluginHub.putListener (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:153:20)
  at Object.putListener (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:234:28)
  at CallbackQueue.assign.notifyAll (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/CallbackQueue.js:65:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
  at ReactReconcileTransaction.Mixin.closeAll (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:202:25)
  at ReactReconcileTransaction.Mixin.perform (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:149:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at ReactUpdatesFlushTransaction.assign.perform (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:86:38)
  at Object.flushBatchedUpdates (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:147:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:202:25)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:149:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
  at Object.enqueueUpdate (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:176:22)
  at enqueueUpdate (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactUpdateQueue.js:24:16)
  at Object.ReactUpdateQueue.enqueueForceUpdate (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactUpdateQueue.js:143:5)
  at FileTree.ReactComponent.forceUpdate (/Users/jpnath/.atom/packages/nuclide/node_modules/react/lib/ReactComponent.js:86:16)
  at /Users/jpnath/.atom/packages/nuclide/pkg/nuclide/file-tree/components/FileTree.js:97:17
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at Immediate._onImmediate (/Users/jpnath/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:290:29)
  at processImmediate [as _immediateCallback] (timers.js:374:17)

**Comment by ssorallen** [comment] 2016-02-10 18:18
@peramsathyam Which release are you using? Are you running from source?

**Comment by scherler** [comment] 2016-02-18 15:26
what is your NODE_ENV? 

If production try 

```
NODE_ENV=develope atom
```

**Comment by deepupathak** [comment] 2016-04-02 06:20
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
at r (49d6498….js?meteor_js_resource=true:85)
at Object.ee.findComponentRoot (49d6498….js?meteor_js_resource=true:90)
at Object.ee.findReactNodeByID (49d6498….js?meteor_js_resource=true:90)
at Object.l as getNode
at E.Mixin._updateDOMProperties (49d6498….js?meteor_js_resource=true:88)
at E.Mixin.updateComponent (49d6498….js?meteor_js_resource=true:88)
at E.Mixin.receiveComponent (49d6498….js?meteor_js_resource=true:88)
at Object.i.receiveComponent (49d6498….js?meteor_js_resource=true:90)
at E._updateRenderedComponent (49d6498….js?meteor_js_resource=true:88)
at E._performComponentUpdate (49d6498….js?meteor_js_resource=true:88)

<h3>Installed Packages</h3>

meteor-base                            # Packages every Meteor app needs to have
mobile-experience                   # Packages for a great mobile UX
mongo                                     # The database Meteor supports right now
blaze-html-templates               # Compile .html files into Meteor Blaze views
session                                    # Client-side reactive dictionary for your app
jquery                                      # Helpful client-side library
tracker                                     # Meteor's client-side reactive programming library
standard-minifiers                   # JS/CSS minifiers run for production mode
es5-shim                                 # ECMAScript 5 compatibility for older browsers.
ecmascript                              # Enable ECMAScript2015+ syntax in app code
kadira:flow-router
kadira:react-layout
react
twbs:bootstrap
pagebakers:ionicons
fortawesome:fontawesome
coniel:react-form-handler
aldeed:simple-schema
universe:react-bootstrap
accounts-ui
accounts-password
accounts-base
email
react-runtime@=0.14.3
cfs:standard-packages
cfs:gridfs
cfs:graphicsmagick
