### ISSUE TITLE
File-icons don't work once Nuclide is installed

### ISSUE THREAD

**Issue by noah-wisch** [facebook/nuclide#1094] opened 2017-04-11 01:42 UTC
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

### Expected Behavior
The file-icons should still work

### Actual Behavior
They do not, stock Nuclide file icons are shown on the file tree

### Versions
* Atom: Most recent
* Nuclide: Most recent

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by shushz** [comment] 2017-04-13 16:38
It's a duplicate of https://github.com/facebook/nuclide/issues/951
Nuclide uses its own implementation of the tree view (file-tree in Nuclide) and it does not consume the `atom.file-icons` service. It should not be too hard a change, but it's also a low priority one.
I'll review a PR on this if somebody's feeling like contributing it.

**Closed by shushz** 2017-04-13 16:38 UTC
