### ISSUE TITLE
Installing “nuclide@0.125.0” failed.

### ISSUE THREAD

**Issue by ManoloPina** [facebook/nuclide#427] opened 2016-03-23 19:36 UTC
npm WARN engine nuclide@0.125.0: wanted: {"atom":">=1.5.3","node":">=4.1.1"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/ManoloPina/.atom/.apm/.apmrc" "--userconfig" "/Users/ManoloPina/.atom/.apmrc" "install" "/private/var/folders/11/v2l9rt091tdcpvxm1p6104g00000gp/T/d-116223-5255-14e5n7m/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3

npm ERR! version not found: relative-date@1.1.2
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/11/v2l9rt091tdcpvxm1p6104g00000gp/T/apm-install-dir-116223-5255-12zl9or/npm-debug.log

**Comment by jasonhero** [comment] 2016-03-23 20:39
Having the same issue here too.

**Comment by mreschke** [comment] 2016-03-24 01:32
yeah, relative-date is only available at version 1.1.3

**Comment by jhristu** [comment] 2016-03-24 02:39
This is a dupe of https://github.com/facebook/nuclide/issues/422

**Comment by denis-mludek** [comment] 2016-03-24 23:48
Yeah, same here :(

**Comment by hansonw** [comment] 2016-03-25 05:29
We just pushed 0.126.0 which solves this. cc @zertosh

**Closed by hansonw** 2016-03-25 05:29 UTC

**Comment by zertosh** [comment] 2016-03-25 06:55
Yup (see https://github.com/facebook/nuclide/releases/tag/v0.126.0). That went out at 2016-03-25T00:08:37Z. So ~7hrs ago.
