### ISSUE TITLE
Treeview div is half hidden.

### ISSUE THREAD

**Issue by ValliusDax** [facebook/nuclide#1504] opened 2018-04-22 21:03 UTC
![screenshot from 2018-04-22 21-46-59](https://user-images.githubusercontent.com/6316940/39099841-a43174ee-4678-11e8-9818-84c07bda4a1b.png)

This is some odd behavior that I haven't been able to resolve where the file tree is twice the width it should be and the right hand half of the file tree is hidden behind the main panel. This makes scrolling impossible as the scrollbar is also hidden.

I've tried reinstalling both atom and nuclide, clearing all packages, resetting things, tried disabling GPU, nothing seems to be able to solve it.

Still happening on latest set of releases (Atom 1.26.0 and Nuclide 0.297.0).

Any suggestions on what I might try next?

**Comment by matthewwithanm** [comment] 2018-04-23 18:45
Thanks for the report @ValliusDax! This is the first we've seen this AFAIK. @captbaritone you haven't seen this/have any ideas, right?

**Comment by ValliusDax** [comment] 2018-04-24 20:37
@captbaritone 
I can confirm both that I had 200% scaling turned on (a 15" 3200x1800 is unreadable otherwise) and that #1501 does fix this for me also.

:grinning:

**Comment by captbaritone** [comment] 2018-04-24 20:40
Thanks! I'll close this issue as a dupe of #1379.

**Closed by captbaritone** 2018-04-24 20:40 UTC
