### ISSUE TITLE
Uncaught TypeError: Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by adam-siton** [facebook/nuclide#505] opened 2016-05-19 07:52 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.138.0

### Stack Trace

Uncaught TypeError: Cannot read property 'render' of undefined

```
At /Users/adam/.atom/packages/nuclide/pkg/nuclide-remote-projects/lib/RemoteProjectsController.js:161

TypeError: Cannot read property 'render' of undefined
  at RemoteProjectsController._renderStatusBar (/Users/adam/.atom/packages/nuclide/pkg/nuclide-remote-projects/lib/RemoteProjectsController.js:161:67)
  at RemoteProjectsController._updateConnectionStatus (/Users/adam/.atom/packages/nuclide/pkg/nuclide-remote-projects/lib/RemoteProjectsController.js:92:14)
  at later (/Users/adam/.atom/packages/nuclide/pkg/nuclide-commons/lib/debounce.js:41:23)

```

### Commands

```
     -0:22.3.0 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "remoteProjectsConfig": []
  }
}
```

### Installed Packages

```coffee
# User
atom-react-native-css, v1.0.0
hyperclick, v0.0.35
language-babel, v2.20.10
language-ocaml, v1.1.2
nuclide, v0.138.0
react, v0.15.0
react-snippets, v0.4.2
tool-bar, v0.1.9

# Dev
No dev packages
```

**Comment by ssorallen** [comment] 2016-05-19 16:44
Does this still happen after restarting Atom? After an update, packages typically need Atom to be restarted because it maintains some state that might not be cleared properly when installing new versions.

**Comment by shushz** [comment] 2016-05-19 17:27
Duplicate of  https://github.com/facebook/nuclide/issues/501 and https://github.com/facebook/nuclide/issues/500

**Closed by shushz** 2016-05-19 17:27 UTC
