### ISSUE TITLE
Nuclide 0.270.0 doesnt have react native Options in command pallete.

### ISSUE THREAD

**Issue by HessiPard** [facebook/nuclide#1399] opened 2017-12-07 13:31 UTC
### Issue and Steps to Reproduce
after updating nuclide to 0.270.0 version, the start packager and other stuffs of react native gone.

### Versions
* Atom: 1.22.1
* Nuclide: 0.270.0
* Client OS: Windows 10

**Comment by pelmers** [comment] 2017-12-07 16:42
duplicate of #1392

**Closed by pelmers** 2017-12-07 16:42 UTC

**Comment by HessiPard** [comment] 2017-12-07 16:47
Thanks ... However the docs need to be updated as soon as possible ..
Good job for this awesome package !
