### ISSUE TITLE
React native console.log not showing in the console view.

### ISSUE THREAD

**Issue by nanandn** [facebook/nuclide#899] opened 2016-11-22 01:48 UTC
The log messages printed from the application using console.log are not showing the 'Console' view. I only see messages from React Native Packager. I started the 'Logs' as explained in https://nuclide.io/docs/platforms/ios/#simulator-logs. 

### Versions
* Atom: 1.12.4
* Nuclide: 0.183.0
* Client OS: macOS 10.12.1

### Additional Details
* Installed packages (`apm ls --installed`):

├── atom-beautify@0.29.13
├── atom-formatter-jsbeautify@1.1.2
├── atom-material-ui@1.3.6
├── autoclose-html@0.23.0
├── git-plus@5.25.3
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.48.4
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── merge-conflicts@1.4.4
├── nuclide@0.183.0
├── nuclide-format-js@0.0.36
├── sort-lines@0.14.0
└── tool-bar@1.0.1

**Comment by tsenterd** [comment] 2016-11-29 14:34
hey just curious are you getting any errors in the console? @nanandn

**Comment by matthewwithanm** [comment] 2016-11-29 22:14
Hey @nanandn! Do you see the logs if you relax the "tags to include" setting under "Nuclide-ios-simulator-logs"?

<img width="905" alt="screen shot 2016-11-29 at 2 13 45 pm" src="https://cloud.githubusercontent.com/assets/126263/20731180/1bebf314-b63e-11e6-9125-517ee31407fe.png">

**Comment by nanandn** [comment] 2016-11-30 04:40
@tsenterd I am not seeing any errors in the console.

**Comment by nanandn** [comment] 2016-11-30 04:40
@matthewwithanm Thanks. yes The log shows once I relax the setting. I changed it to '^(.*)$' and I see the logs now. Is this a right setting? What are those tags?

**Comment by nanandn** [comment] 2016-11-30 04:50
@matthewwithanm Thank you for the explanation.

**Comment by jtokoph** [comment] 2017-01-20 04:01
Possibly related:

- When remote js debugging is disabled `console.log` messages appear in the console.
- When remote js debugging is enabled and connected to Chrome, `console.log` messages appear in the Chrome devtool console.
- **When remote js debugging is enabled and connected to the Nuclide debugger, `console.log` messages don't appear anywhere.**

Is there some way to get the logged messages while the debugger is running?

**Comment by wellyshen** [comment] 2017-02-06 09:12
@matthewwithanm What's the right way to set the "tags to include" ? Currently I just follow the @nanandn 's solution, set it to "^(.*)$".

**Comment by yungsters** [comment] 2017-02-28 00:28
@nanandn Can you confirm that this is only an issue when remote debugging via the Nuclide debugger (as @jtokoph described)?

**Comment by wellyshen** [comment] 2017-02-28 05:47
When does this issue will be fixed?

**Comment by alexhhn** [comment] 2017-03-02 13:51
Any news about this issue?

**Comment by matthewwithanm** [comment] 2017-03-03 20:53
@wellyshen @alexhhn Sorry, @yungsters is trying to help debug.

**Comment by yungsters** [comment] 2017-03-03 21:11
@nanandn, @wellyshen, or @alexhhn: Can any of you confirm that this is only an issue when remote debugging via the Nuclide debugger (as @jtokoph described)?

**Comment by wellyshen** [comment] 2017-03-04 06:26
@yungsters the log can run on Chrome console view but not on Ncuclide, does the info enough?

**Comment by alexhhn** [comment] 2017-03-07 16:18
The same as wellyshen

**Comment by anarasimhan** [comment] 2017-03-07 16:55
@yungsters The console log don't appear even if you are not using the debugging. When I change the tags to ''^(.*)$' it works.

**Comment by yungsters** [comment] 2017-03-08 05:11
@wellyshen, @alexhhn, and @anarasimhan: Thanks for the extra information.

I tried reproducing the problem, but I am unable to. Can you try looking in the iOS Simulator's System Log (Menu Bar > Debug > Open System Log...) and look for your `console.log(...)` messages there? If so, can you share what those are?

For example, I see the following in my System Log:

```
Mar  7 21:06:23 yungsters-mbp Facebook[71888]: 2017-03-07 21:06:23.596 [info][core.react][tid:com.facebook.react.JavaScript][] Expected console log message.
```

**Comment by wellyshen** [comment] 2017-03-08 06:54
@yungsters 

It that what you mean?

<img width="966" alt="2017-03-08 2 53 15" src="https://cloud.githubusercontent.com/assets/21308003/23693371/1a8192bc-040f-11e7-9b81-846b8ac337f7.png">

Please note, I use `^(.*)$` instead the default settings

**Comment by yungsters** [comment] 2017-03-08 07:31
@wellyshen Select your iOS Simulator. In the Menu Bar, under the Debug menu, select the "Open System Log..." option. This should open a new window with System Logs.

From there, use the search feature to look for your console.log message. Please share the entirety of that log message.

**Comment by wellyshen** [comment] 2017-03-08 07:40
@yungsters Here's my log, does the info enough? Please note, I'm use `^(.*)$` instead of the default

<img width="601" alt="2017-03-08 3 39 00" src="https://cloud.githubusercontent.com/assets/21308003/23694580/95ad36ac-0415-11e7-8c8b-995a32f31da1.png">

**Comment by yungsters** [comment] 2017-03-08 07:46
@wellyshen Hmm, looks like the iOS Simulator logs are for some reason missing the standard tags that Nuclide uses as the default filter. Thanks for the help.

**Comment by wellyshen** [comment] 2017-03-08 07:47
@yungsters It seems my log on iOS's console.log works fine, but it can't show on the Nuclide's console view. Unless I use the `^(.*)$` instead of the default settings.

**Comment by chipanda** [comment] 2017-03-20 06:26
I did not seen the console.log in nuclide console with errors in chrome console:./host/InspectorFrontendHost.js:653 Incompatible embedder: method InspectorFrontendHost.platform is missing. Using stub instead.

**Comment by wellyshen** [comment] 2017-03-22 14:33
Any update for this?

**Comment by hfossli** [comment] 2017-04-05 12:01
Should it work from device as well? Does those settings in `iOS Simulator Logs` apply to device as well? I guess not?

**Comment by wellyshen** [comment] 2017-04-08 08:28
Any update for this?

**Comment by cristiantx** [comment] 2017-04-09 18:23
I'm having the same issue as @chipanda https://github.com/facebook/nuclide/issues/899#issuecomment-287685554. Console with a lot of errors and inspectors doesn't seem to work. If I use the default chrome debugger that opens from packager it shows the logs ok.

![image](https://cloud.githubusercontent.com/assets/313035/24839866/7e7fedbc-1d38-11e7-8120-cb031511c444.png)

**Comment by agersoncgps** [comment] 2017-04-29 13:38
I do not get logs in Atom / Nuclide with or without the remote debugger enabled. CHanging the tags to include does fix it.

**Comment by mesbahsabur** [comment] 2017-04-30 01:12
+1

**Comment by wellyshen** [comment] 2017-05-23 12:40
Any update?

**Comment by yungsters** [comment] 2017-05-24 03:43
I think I have it figured out.

Internally at Facebook, we have configured React Native via `RCTSetLogFunction` to log not only the message, but also `[core.react]`. This is how we differentiate logs coming from React Native apart from the rest of our app.

@matthewwithanm Is there a mechanism to configure the default tag filter in Nuclide differently internally? The current default is very specific to our internal environment.

**Solution:**Use `^(.*)$` as your tag filter in Nuclide.

**Comment by matthewwithanm** [comment] 2017-05-24 03:54
@yungsters We don't tag messages at all in open source? Having no filter (`^.*$`) isn't really a solution because the console gets spammed with irrelevant logs.

**Comment by yungsters** [comment] 2017-05-24 03:56
@matthewwithanm We do not. If you take a look at https://github.com/facebook/nuclide/issues/899#issuecomment-284969651, the output is entirely up to how developers happen to integrate React Native into their mobile apps.

**Comment by matthewwithanm** [comment] 2017-05-24 04:10
Ugh. Maybe we have to go back to tailing that one random file. I'd much prefer having React's messages tagged in some way that we could identify though. @frantic do you have any ideas here?

**Comment by wellyshen** [comment] 2017-07-22 05:47
Sorry, may I know any update for this issue?

**Comment by matthewwithanm** [comment] 2017-07-24 17:05
@wellyshen No updates currently, sorry! For now, you need to change the filter like you're already doing.

**Comment by wellyshen** [comment] 2017-07-25 02:22
Okay, I just want to remind that console.log is one of the important debug way for many developers. We're eager for hearing the fixing of this issue.

**Comment by winsonet** [comment] 2017-08-02 16:15
I have the same issue, but I don't want to set the log filter to ^(.*)$, because it will show a lot of other system messages and keep to loop to show :(

**Comment by wellyshen** [comment] 2017-10-02 11:42
use `^(.*)$` on xCode 9 not work...

**Comment by mostafaeweda** [comment] 2017-11-17 23:07
That should be fixed in the latest RN debugger release.

**Closed by mostafaeweda** 2017-11-17 23:07 UTC

**Comment by wellyshen** [comment] 2017-11-18 04:03
@modocache Which version of nuclide?

**Comment by mostafaeweda** [comment] 2017-11-18 04:15
It’s currently in master  (if you build from source) and will be in next week’s release

**Comment by wellyshen** [comment] 2017-11-18 04:16
@mostafaeweda OK, thank you a lot ;)

**Comment by jayeshjain24** [comment] 2017-12-18 09:20
This is the best link that explains logging with chrome devtools : https://codeburst.io/react-native-debugging-tools-3a24e4e40e4
