### ISSUE TITLE
Unwanted tool bar cannot be removed 

### ISSUE THREAD

**Issue by moogus** [facebook/nuclide#797] opened 2016-10-13 07:39 UTC
### Issue and Steps to Reproduce
A tool bar has recently been added to nuclide at the top of the environment, I can't disable it in settings I can't remove it completely, instead I have to hide it every time I open the editor.  Any ideas on how to remove it for good, or disable it?

### Expected Behavior
Should be able to uninstall

### Actual Behavior
Can't uninstall

### Versions
* Atom:1.11.1
* Nuclide:0.175.0
* Client OS:Mac OSX Sierra

### Additional Details
![image](https://cloud.githubusercontent.com/assets/4889659/19340299/1a0d35f0-9120-11e6-9a79-dd5718ccbf26.png)

**Comment by matthewwithanm** [comment] 2016-10-13 17:14
Hey @moogus! If you hide it, that'll be remembered for that project.

I'll look into adding a setting that hides it by default though.

**Comment by matthewwithanm** [comment] 2016-10-13 17:29
Gonna close this since it's a dupe of #768.

**Closed by matthewwithanm** 2016-10-13 17:29 UTC
