### ISSUE TITLE
Atom freezes on settings/packages screen when nuclide is installed

### ISSUE THREAD

**Issue by akaRem** [facebook/nuclide#241] opened 2015-11-10 18:18 UTC
I've installed only nuclide (full) package and have problems with huge operational degradation:
when I open settings/packages, 
- Atom can't list anything
- UI is totally frozen (click anywhere -> no response).

When i don't visit settings/packages, app is laggy (impossible to use) and hangs over some time (~5-10min)

apm list                        
Built-in Atom packages (90)
├── about@1.1.0
├── archive-view@0.61.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.22.0
├── autocomplete-snippets@1.7.1
├── autoflow@0.26.0
├── autosave@0.22.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.0.0
├── base16-tomorrow-light-theme@1.0.0
├── bookmarks@0.38.0
├── bracket-matcher@0.78.0
├── command-palette@0.36.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.185.0
├── fuzzy-finder@0.90.0
├── git-diff@0.56.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.55.0
├── incompatible-packages@0.25.0
├── keybinding-resolver@0.33.0
├── language-c@0.48.0
├── language-clojure@0.18.0
├── language-coffee-script@0.42.0
├── language-csharp@0.11.0
├── language-css@0.34.0
├── language-gfm@0.81.0
├── language-git@0.10.0
├── language-go@0.39.0
├── language-html@0.42.0
├── language-hyperlink@0.14.0
├── language-java@0.16.0
├── language-javascript@0.96.0
├── language-json@0.17.0
├── language-less@0.28.2
├── language-make@0.19.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.0
├── language-perl@0.30.0
├── language-php@0.30.0
├── language-property-list@0.8.0
├── language-python@0.40.0
├── language-ruby@0.60.0
├── language-ruby-on-rails@0.23.0
├── language-sass@0.42.0
├── language-shellscript@0.19.0
├── language-source@0.9.0
├── language-sql@0.17.0
├── language-text@0.7.0
├── language-todo@0.27.0
├── language-toml@0.16.0
├── language-xml@0.33.0
├── language-yaml@0.24.0
├── line-ending-selector@0.2.0
├── link@0.31.0
├── markdown-preview@0.154.0
├── metrics@0.53.0
├── notifications@0.59.0
├── one-dark-syntax@1.1.1
├── one-dark-ui@1.1.5
├── one-light-syntax@1.1.1
├── one-light-ui@1.1.5
├── open-on-github@0.38.0
├── package-generator@0.40.0
├── release-notes@0.53.0
├── settings-view@0.230.0
├── snippets@0.100.0
├── solarized-dark-syntax@0.38.1
├── solarized-light-syntax@0.22.1
├── spell-check@0.61.0
├── status-bar@0.79.0
├── styleguide@0.44.0
├── symbols-view@0.109.0
├── tabs@0.84.0
├── timecop@0.33.0
├── tree-view@0.190.0
├── update-package-dependencies@0.10.0
├── welcome@0.30.0
├── whitespace@0.31.0
└── wrap-guide@0.38.0

/Users/me/.atom/packages (35)
├── hyperclick@0.0.32
├── nuclide-arcanist@0.0.32
├── nuclide-blame@0.0.32
├── nuclide-blame-provider-hg@0.0.32
├── nuclide-blame-ui@0.0.32
├── nuclide-buck-files@0.0.32
├── nuclide-clang-atom@0.0.32
├── nuclide-code-format@0.0.32
├── nuclide-debugger-atom@0.0.32
├── nuclide-debugger-hhvm@0.0.32
├── nuclide-debugger-lldb@0.0.32
├── nuclide-diagnostics-store@0.0.32
├── nuclide-diagnostics-ui@0.0.32
├── nuclide-diff-view@0.0.32
├── nuclide-file-tree@0.0.32
├── nuclide-file-tree-deux@0.0.32
├── nuclide-file-watcher@0.0.32
├── nuclide-find-references@0.0.32
├── nuclide-flow@0.0.32
├── nuclide-format-js@0.0.32
├── nuclide-fuzzy-filename-provider@0.0.32
├── nuclide-hack@0.0.32
├── nuclide-hack-symbol-provider@0.0.32
├── nuclide-hg-repository@0.0.32
├── nuclide-installer@0.0.32
├── nuclide-language-hack@0.0.32
├── nuclide-move-pane@0.0.32
├── nuclide-objc@0.0.32
├── nuclide-ocaml@0.0.32
├── nuclide-open-filenames-provider@0.0.32
├── nuclide-quick-open@0.0.32
├── nuclide-remote-projects@0.0.32
├── nuclide-test-runner@0.0.32
├── nuclide-toolbar@0.0.32
└── nuclide-type-hint@0.0.32

MBP 13r i52.9/8G
OSX 10.11.1 (15B42)
Atom 1.1.0

**Comment by akaRem** [comment] 2015-11-10 18:21
In dev mode works slightly better, but have these console messages:

/Users/me/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/warning.js:48 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset
index.js:46 Window load time: 14920ms
/Users/me/.atom/packages/nuclide-fuzzy-filename-provider/node_modules…modules/nuclide-path-search/node_modules/nuclide-task/lib/bootloader.js:41 TASK(86258): [2015-11-10T18:19:25.839Z] [ERROR] nuclide - Error while talking to watchman:  { [Error: Command failed: /bin/sh -c watchman get-sockname
/bin/sh: watchman: command not found
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c watchman get-sockname' }

**Comment by akaRem** [comment] 2015-11-10 18:25
installing watchman helps a little, but Atom is still laggy, slow, useless and freeze over time

**Comment by akaRem** [comment] 2015-11-10 18:52
manual killing of packages:

cd ~/.atom/packages 
rm -rf ./nuclide-blame*

no changes in behavior
Window load time: 14273ms

rm -rf ./nuclide-file* 

no changes in behavior
Window load time: 14905ms

rm -rf ./nuclide-installer

no changes in behavior
Window load time: 14142ms

rm -rf ./nuclide-hg-repository

no changes in behavior
Window load time: 13511ms

rm -rf ./nuclide-clang-atom ./nuclide-language-hack ./nuclide-hack ./nuclide-hack-symbol-provider
no changes in behavior
Window load time: 9765ms

rm -rf ./nuclide-diagnostics*
no changes
Window load time: 9197ms

rm -rf nuclide-code-format ./nuclide-diff-view ./nuclide-fuzzy-filename-provider ./nuclide-open-filenames-provider ./nuclide-toolbar
Window load time: 8707ms

rm -rf ./nuclide-debugger*

**Comment by akaRem** [comment] 2015-11-10 19:00
rm -rf ./hyperclick ./nuclide-buck-files ./nuclide-flow ./nuclide-move-pane ./nuclide-ocaml ./nuclide-remote-projects 
better and does not hang on packages
Window load time: 1709ms

so at this poin I have only

/Users/me/.atom/packages (7)
├── nuclide-arcanist@0.0.32
├── nuclide-find-references@0.0.32
├── nuclide-format-js@0.0.32
├── nuclide-objc@0.0.32
├── nuclide-quick-open@0.0.32
├── nuclide-test-runner@0.0.32
└── nuclide-type-hint@0.0.32

and atom works

**Comment by bkbelton** [comment] 2015-11-10 20:47
Are you on Windows? I had same issue, and upon uninstalling discovered that the pathnames to the nuclide packages were too long for windows.

**Comment by akaRem** [comment] 2015-11-11 17:31
@bkbelton OSX

**Comment by VicYork** [comment] 2015-11-11 18:39
I'm having the same issue. It seems to work a bit better when I delete all other packages that aren't added by Nuclide, but the setting pane still freezes.

**Comment by kh9n** [comment] 2015-11-13 04:35
Same issue here (OS X), after remove all nuclide package, atom back to work.

**Comment by kenashworth** [comment] 2015-11-13 15:13
Wow, this is an egregiously bad bug.

**Comment by akaRem** [comment] 2015-11-13 15:43
@VicYork I had this problem on my regular installation (with "other packages"). Then I decided to reproduce on clean environment (and posted results here). As you see, the problem is somewhere in nuclide packages.

@kh9n I fixed my problem in the same way — just removed all `nuclide-*`  packages from my Atom.
But I think guys from facebook won't suggest this solution. :)

@kenashworth Yes.
But after some research I found that I don't really need `nuclide-*` packages.
They came in bundle, so many things are installed but useless for me. And other non-useless packages are poorly maintained and I found better replacements.

**Comment by damianesteban** [comment] 2015-11-15 21:38
This is a serious issue and it has been going on for awhile.  I don't know why it hasn't been addressed or acknowledged yet.  Atom is slow enough as it is...

**Comment by metaljoe** [comment] 2015-11-17 11:58
Not wanting to say a "me too", but I'm getting the same here - not a good first experience of Nuclide. OS X as well.

**Comment by akaRem** [comment] 2015-11-18 20:17
@damianesteban @metaljoe (offtop):
Do you use full nuclide package?
Does nuclide have any special feature which is not available in any other package or packages?

**Comment by damianesteban** [comment] 2015-11-20 18:54
@akaRem   I haven't been able to use Nuclide as it freezes up and does not finish installing the packages.

As for the supposed features of Nuclide, you can read about them here (again, I can't confirm their functionality as it does not install properly):

http://nuclide.io/docs/setup/

With the recent updates to Visual Studio Code (specifically the ability to install extensions, which include Flow and ES6 support), that will be my go to JavaScript editor.  Maybe I'll try out Nuclide when I can install it.

**Comment by ssorallen** [comment] 2015-11-20 20:24
We haven't ignored this problem even though we haven't given much response. We have some large organizational changes that aim to dramatically simplify Nuclide installation and solve this problem for good. We don't have an exact timeline, but it is coming in the near term. We will update all relevant tasks when we have more info.

**Comment by jernejstrasner** [comment] 2015-11-21 11:27
Same issue here (on OSX). Just spins the CPU while being completely unresponsive.

**Comment by metaljoe** [comment] 2015-11-21 14:39
@akaRem I thought I'd give it a go partly because of the Mercurial support, and partly out of interest to see how it compares to standard Atom. I installed the full installation.

Although the nuclide packages install just fine, the editor is unusable once installed. It hits 100% CPU usage, with spinny beachball of death - I left it for about half an hour once to see if it eventually sorted itself out, but still unresponsive. After removing the nuclide packages via apm, everything is back to normal and Atom is usable again.

**Comment by ssorallen** [comment] 2015-11-23 21:04
Closing as a duplicate of #84.

There is major refactoring in progress that will dramatically improve the installation process. I'll use #84 as the place to discuss it when it gets closer to landing.

**Closed by ssorallen** 2015-11-23 21:04 UTC
