### ISSUE TITLE
Show debugger makes nothing

### ISSUE THREAD

**Issue by albertosgz** [facebook/nuclide#1465] opened 2018-02-15 08:22 UTC
### Issue and Steps to Reproduce
I can't display the debugger panel. The Nuclide->debugger->show doesn't work. The Nuclide Home->PHP Debugger->Try it makes nothing, even from Developer Tools console.

### Expected Behavior
Configuration panel for debugger should came out.

### Actual Behavior
Nothing happens.

### Versions
* Atom: 1.24.0
* Nuclide:0.283.0
* Client OS:"Linux Mint 18.3 Sylvia" Linux nox 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Server OS (optional):"Linux Mint 18.3 Sylvia" Linux nox 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Additional Details
* Installed packages (`apm ls --installed`):
├── MagicPython@1.0.12
├── atom-beautify@0.30.9
├── atom-ide-ui@0.8.1 (disabled)
├── busy-signal@1.4.3
├── color-picker@2.2.5
├── file-icons@2.1.16
├── git-plus@7.10.0
├── highlight-selected@0.13.1
├── ide-php@0.7.5
├── intentions@1.1.5
├── keyboard-scroll@0.7.0
├── language-babel@2.83.4
├── language-blade@0.38.0
├── language-graphql@0.9.0
├── language-haskell@1.17.3
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── language-vue@0.23.1
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.1
├── linter-php@1.5.1
├── linter-ui-default@1.6.10 (disabled)
├── lipsum@0.1.0
├── minimap@4.29.7
├── minimap-find-and-replace@4.5.2
├── minimap-highlight-selected@4.6.1
├── multi-cursor@2.1.5
├── native-ui@0.25.2
├── nuclide@0.283.0
├── nuclide-format-js@0.0.44
├── pigments@0.40.2
├── project-manager@3.3.5
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── teletype@0.8.0
├── todo-show@2.1.0 (disabled)
└── tool-bar@1.1.6

**Comment by pelmers** [comment] 2018-02-15 17:53
duplicate of #1461 , see instructions there

**Closed by pelmers** 2018-02-15 17:53 UTC
