### ISSUE TITLE
install nuclide failed

### ISSUE THREAD

**Issue by bluesky0109** [facebook/nuclide#423] opened 2016-03-23 04:36 UTC
### Issue and Steps to Reproduce
use atom to install nuclide.

### Expected Behavior
use atom to install nuclide.

### Actual Behavior
Receive this error: "Installing “nuclide@0.125.0” failed".
Expanded details:
npm WARN engine nuclide@0.125.0: wanted: {"atom":">=1.5.3","node":">=4.1.1"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/sky/.atom/.apm/.apmrc" "--userconfig" "/Users/sky/.atom/.apmrc" "install" "/private/var/folders/r9/6ypvysqn6kgfn71dm1myn2sr0000gn/T/d-116223-3571-zcn3zi/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3

npm ERR! version not found: relative-date@1.1.2
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/r9/6ypvysqn6kgfn71dm1myn2sr0000gn/T/apm-install-dir-116223-3571-1acy5dn/npm-debug.log

### Versions
* Atom:1.6.0
* Nuclide:0.125.0
* Client OS:OS X 10.11.4
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
/Users/sky/.atom/packages (0)
└── (empty)

 ~ node -v
v5.5.0

~ npm -v
3.8.2

**Comment by ecstasy2** [comment] 2016-03-23 06:02
+1

**Comment by mikaoelitiana** [comment] 2016-03-23 06:51
I have the same issue. Latest Atom version is installed

**Comment by p1xelHer0** [comment] 2016-03-23 10:48
I have the exact same issue

**Comment by kileras** [comment] 2016-03-23 11:42
This is because the owner of relative-date unpublished it form npm [like many other modules](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos).

Someone else already add the module back to the registry but it is a newer version 1.1.3 so basically the only thing that need to be done is to use that one

**Comment by sushant23** [comment] 2016-03-23 11:46
@kileras how to use newer version 1.1.3 could you please explain?

**Comment by kileras** [comment] 2016-03-23 11:50
You only need to change the version in package.json form 1.1.2 to 1.1.3, but this seems to be fixed in the last commit, someone just add relative date to the source and remove the dep form package.json so its fixed in master, they just need to update it in the atom registry....

**Comment by sushant23** [comment] 2016-03-23 12:16
I am sorry I am very new at this, shouldn't I be changing /opt/atom/resources/app/apm/package.json?

**Comment by jsg2021** [comment] 2016-03-23 15:41
This is duplicate of #422

**Closed** 2016-03-25 05:31 UTC
