### ISSUE TITLE
windows10 nuclide 0.118 on atom treeview don't show the tree,please fix

### ISSUE THREAD

**Issue by tonytbl** [facebook/nuclide#369] opened 2016-02-21 13:41 UTC
### Issue and Steps to Reproduce
windows10 nuclide 0.118 on atom treeview don't show the tree,please fix

 

### Versions
* Atom:1.5.3
* Nuclide:0.118
* Client OS:win10
* Server OS (optional):

**Comment by viatsko** [comment] 2016-02-21 13:42
Nuclide is incompatible with Windows at the moment. :(

Please follow this issue for updates https://github.com/facebook/nuclide/issues/321

**Comment by shushz** [comment] 2016-02-21 16:19
Yes, unfortunately Windows is not yet fully supported.
Closing as duplicate of https://github.com/facebook/nuclide/issues/321

**Closed by shushz** 2016-02-21 16:19 UTC

**Comment by ssorallen** [comment] 2016-02-22 00:13
@tonytbl Did it work in previous versions?
