### ISSUE TITLE
Renaming directory by changing caps deletes directory

### ISSUE THREAD

**Issue by wolverineks** [facebook/nuclide#1515] opened 2018-05-04 20:30 UTC
### Issue and Steps to Reproduce
1. Open Atom with Nuclide plugin enabled
2. From File Tree, create new folder named `deleteme`
3. From File Tree, rename `deleteme` -> `DELETEME`

### Expected Behavior
Directory should be renamed

### Actual Behavior
`deleteme`, `DELETEME`, and all sub files/folders are deleted

### Versions
* Atom: 1.26.1
* Nuclide: 0.301.1
* Client OS: MacOS

### Additional Details
├── MagicPython@1.0.12
├── atom-beautify@0.32.2
├── atom-ide-ui@0.11.1
├── autocomplete-paths@2.12.2
├── busy-signal@1.4.3
├── editorconfig@2.2.2
├── file-icons@2.1.19
├── fonts@3.0.3
├── git-time-machine@1.5.9
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── intentions@1.1.5
├── language-babel@2.85.0
├── language-graphql@0.10.1
├── language-haskell@1.17.6
├── language-ini@1.19.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-sml@0.7.0
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.1
├── linter-ui-default@1.7.1 (disabled)
├── linter-xo@0.26.0
├── nuclide@0.301.1
├── nuclide-esformatter@0.3.1 (disabled)
├── nuclide-format-js@0.0.45
├── nuclide-test-runner-mocha@0.1.1 (disabled)
├── pigments@0.40.2
├── platformio-ide-terminal@2.8.1
├── prettier-atom@0.53.0
├── redux-devtools@0.5.1
├── set-syntax@0.4.0
├── smart-tab-name@1.0.5
├── snippet-generator-plus@0.1.2
├── sort-lines@0.18.0
├── teletype@0.13.2
├── tester@1.4.0
├── tester-jest@1.2.4
├── tester-mocha@1.0.0 (disabled)
├── tool-bar@1.1.7
└── wakatime@7.0.4

**Comment by pelmers** [comment] 2018-05-09 19:38
duplicate of #1434

**Closed by pelmers** 2018-05-09 19:38 UTC
