### ISSUE TITLE
Nuclide ReactNative support

### ISSUE THREAD

**Issue by ColinEberhardt** [facebook/nuclide#211] opened 2015-10-05 05:14 UTC
Hi, I am pretty sure I saw a video a while back where the Nuclide IDE was being used to develop a ReactNative application. Nuclide was able to launch and manage the Xcode simulator.

I've installed Nuclide, but cannot find any plugins that seems to relate to ReactNative. Can someone please point me in the right direction? Thanks!

**Comment by kkganesan** [comment] 2015-10-12 01:20
+1

**Comment by Thorbenandresen** [comment] 2015-10-17 16:17
+1

**Comment by BilalBudhani** [comment] 2015-10-18 16:29
would :heart: to have hands on react native support.

**Comment by jacob-israel-turner** [comment] 2015-10-21 16:23
Duplicate of https://github.com/facebook/nuclide/issues/31

**Comment by idibidiart** [comment] 2015-12-15 05:17
+ 1

**Comment by jamesgpearce** [comment] 2016-03-02 23:52
Closing out with https://www.youtube.com/watch?v=f1Sj48rJE3I&index=13&list=PLb0IAmt7-GS0M8Q95RIc2lOM6nc77q1IY ...

**Closed by jamesgpearce** 2016-03-02 23:52 UTC
