### ISSUE TITLE
Slowly and will crash

### ISSUE THREAD

**Issue by carl1990** [facebook/nuclide#215] opened 2015-10-12 07:04 UTC
when install nuclide in atom 1.0.19 on mac os 10.10 and open a project edit,it will change very slowly and then change to no response and cpu use 104.3%, memory use more than 1G

**Comment by xiekw2010** [comment] 2015-10-12 11:28
+1

**Comment by sirianni** [comment] 2015-10-13 18:57
Same problem here.  I can't even uninstall/disable via the Settings view.

**Comment by mgoffin** [comment] 2015-10-13 21:57
+1

I had Nuclide installed and working before upgrading to El Cap. Now it seems to hang when trying to check for updates to the Nuclide packages. Nuking `~/.atom` and starting from scratch I can install other packages and things will be fine. Once I try to install Nuclide the installer will stop part-way, fans will crank up to max, and the UI will become unresponsive. Restarting after that has the same issues.

**Comment by ssorallen** [comment] 2015-10-14 22:04
Are you hitting this problem when opening the settings view? There was a known problem in settings-view that was fixed (https://github.com/atom/settings-view/issues/555) and will soon be in a release of Atom.

**Comment by guswelter** [comment] 2015-10-18 17:19
+1

No, this happens intermittently without going to settings view. It most often happens after just starting Atom and connecting to Nuclide. If you watch (in OS X Activity Monitor) and wait for the process to go from 105% processor usage down towards 0, then Atom/Nuclide work well again. Sometimes this is a few minutes; sometimes it's a half-hour.

**Comment by guswelter** [comment] 2015-10-20 12:59
This may be a duplicate of https://github.com/facebook/nuclide/issues/199

**Comment by eklavya** [comment] 2015-10-21 17:56
Installed atom to try out react native. Nuclide is in a totally unusable state right now (on mac at least).

**Comment by guswelter** [comment] 2015-10-21 18:05
I built from source, and it resolved the issue completely for me. Here's what I did:
1. On client side, wipe Atom and reinstall (on OS X, be sure to  delete ~/.atom and ~/Library/Application Support/Atom before reinstall)
2. Follow Build from Source instructions at https://github.com/facebook/nuclide/blob/master/README.md
3. On server side (if applicable), remove npm package: npm uninstall -g nuclide-server and then follow Build from Source instructions at https://github.com/facebook/nuclide/blob/master/pkg/nuclide/server/README.md

Temporary solution until the next release.

**Comment by eklavya** [comment] 2015-10-22 12:53
hey @guswelter thanks for the quick response. I tried to build it manually but after installing so many errors popped up that I gave up. I will try again when it's released.

**Comment by hufeng** [comment] 2015-10-24 15:32
+1

**Comment by UnsungHero97** [comment] 2015-10-31 02:18
+1 Atom is completely unusable after running `nuclide-installer`.

Atom v1.1.0
Mac 10.10.5

**Comment by astannard** [comment] 2015-11-02 15:29
Think this is the same as issue #84: I have it down to one of the below packages, try installing these, do it one at a time to work out the culprit, I've not had time to reinstall and uninstall these yet to figure out the guilty party:

nuclide-code-format@0.0.32
nuclide-find-references@0.0.32
nuclide-format-js@0.0.32
nuclide-ocaml@0.0.32
nuclide-toolbar@0.0.32
nuclide-type-hint@0.0.32

**Comment by niieani** [comment] 2015-11-07 13:05
@astannard I've uninstalled one by one, all of the packages you listed, but nothing helped.

**Comment by Kay2dan** [comment] 2015-11-24 18:50
+1
Unfortunately, Atom has become unusable because of this plugin.

**Comment by Staberinde** [comment] 2015-11-25 18:26
+1

**Comment by dsifford** [comment] 2015-11-27 03:09
+1

**Comment by MarkehMe** [comment] 2015-12-07 02:06
Just nuked ```~/.atom``` myself. Can not open Atom at all anymore. Will just install and use alternative packages

**Comment by Luien** [comment] 2015-12-13 06:12
+1

which module run 'apm ls --json --no-color' ?

**Comment by nmote** [comment] 2016-01-14 16:58
Fixed by the unified package: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/

**Closed by nmote** 2016-01-14 16:58 UTC

**Comment by luongs3** [comment] 2018-01-04 08:51
+1
slow omnisearch, and sometimes crash
