### ISSUE TITLE
Failed to activate the nuclide-working-sets package

### ISSUE THREAD

**Issue by levinqdl** [facebook/nuclide#416] opened 2016-03-18 02:21 UTC
### Issue and Steps to Reproduce
When atom starts, "Failed to activate the nuclide-working-sets" appears, and the working sets feature doesn't work.
steps to reproduce:

- update nuclide from 0.124.0 to 0.125.0
- start atom

### Expected Behavior
working sets work as expect

### Actual Behavior
An error report appears when atom start, and the working sets feature dose not work

### Versions
* Atom: 1.6.0
* Nuclide: 0.125.0
* Client OS: OS X 10.11.3
* Server OS (optional):

### Additional Details
* stack trace:
```
AssertionError: Nuclide URIs must contain paths, 'null' found.
    at parse (/Users/xxx/.atom/packages/nuclide/pkg/nuclide-remote-uri/lib/main.js:67:27)
    at normalizePathUri (/Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/uri.js:32:44)
    at WorkingSet.containsDir (/Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSet.js:91:65)
    at /Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsStore.js:272:27
    at Array.some (native)
    at WorkingSetsStore._isApplicable (/Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsStore.js:271:44)
    at /Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsStore.js:258:20
    at Array.forEach (native)
    at WorkingSetsStore._sortOutApplicability (/Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsStore.js:257:19)
    at WorkingSetsStore.updateDefinitions (/Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsStore.js:84:41)
    at /Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/main.js:67:30
    at wrapped (/Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsConfig.js:43:9)
    at Config.module.exports.Config.observeKeyPath (/Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:612:7)
    at Config.module.exports.Config.observe (/Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at Object.observe (/Users/xxx/.atom/packages/nuclide/pkg/nuclide-feature-config/lib/main.js:44:50)
    at WorkingSetsConfig.observeDefinitions (/Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsConfig.js:46:48)
    at new Activation (/Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/main.js:66:51)
    at Object.activate (/Users/xxx/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/main.js:92:16)
    at Package.module.exports.Package.activateNow (/Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at Object.activate (/Users/xxx/.atom/packages/nuclide/lib/main.js:218:31)
    at Package.module.exports.Package.activateNow (/Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Users/xxx/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
```

**Comment by shushz** [comment] 2016-03-18 16:44
@levinqdl Could you please paste the your Working Sets configuration (the "workingSets" array from you Atom --> Open Your Config) and tell which project roots you have mounted?

**Comment by levinqdl** [comment] 2016-03-20 07:29
@shushz 
here is the working sets config:
"nuclide-working-sets":
  workingSets: [
    {
      name: "gamis app"
      active: true
      uris: [
        "/Users/xxx/react-native/GamisApp/android"
        "/Users/xxx/react-native/GamisApp/index.android.js"
        "/Users/xxx/react-native/GamisApp/index.ios.js"
        "/Users/xxx/react-native/GamisApp/ios"
        "/Users/xxx/react-native/GamisApp/views"
      ]
    }
    {
      name: "admin frontend"
      active: false
      uris: [
        "/Users/xxx/IdeaProjects/tuobar-admin/frontend/.babelrc"
        "/Users/xxx/IdeaProjects/tuobar-admin/frontend/__tests__"
        "/Users/xxx/IdeaProjects/tuobar-admin/frontend/js"
        "/Users/xxx/IdeaProjects/tuobar-admin/frontend/package.json"
        "/Users/xxx/IdeaProjects/tuobar-admin/frontend/webpack.config.js"
        "/Users/xxx/IdeaProjects/tuobar-admin/frontend/webpack.production.config.js"
      ]
    }
  ]

**Comment by shushz** [comment] 2016-03-22 16:09
@levinqdl The WS configuration seems fine. Is the issue still reproducible? Also, what project roots do you have mounted in your Nuclide?

**Comment by levinqdl** [comment] 2016-03-23 01:21
@shushz , yes, the issue is still there. The project roots are /Users/xxx/react-native/GamisApp/ and /Users/xxx/IdeaProjects/tuobar-admin/frontend/

**Comment by shushz** [comment] 2016-03-31 18:35
OK. @JoelMarcey reproduced it. The issue is triggered by having the Atom's "About" pane open. Apparently, in some cases at least, having it open adds a virtual directory with unexpected path and that confuses the Working Sets. The next version - v0.128.0 will have a fix for that.

Fixed by https://github.com/facebook/nuclide/commit/2f49bff36f9fa41c7072d2479bc8ad68c1d1a35b

**Closed by shushz** 2016-03-31 18:35 UTC

**Comment by levinqdl** [comment] 2016-04-06 04:32
Thanks a lot, the issue has gone in 0.128.0!
