### ISSUE TITLE
Cannot find module 'nuclide-commons'

### ISSUE THREAD

**Issue by acid009** [facebook/nuclide#253] opened 2015-11-26 13:09 UTC
Can't install nuclide.
Tried to completely reinstall atom with the same result.
Mac OS Yosemite
![_nuclide_error](https://cloud.githubusercontent.com/assets/5305323/11423734/345d1422-9471-11e5-8a93-4c30fd0fbba3.png)

**Comment by dozstudio** [comment] 2015-11-26 13:19
I have exactly the same problem !

**Comment by acid009** [comment] 2015-11-26 13:39
Can we just have nuclide as a separate app not to break default Atom installation ?

**Comment by maopy208** [comment] 2015-11-27 08:17
![image](https://cloud.githubusercontent.com/assets/1468834/11436731/5ec50240-9522-11e5-8334-0066728dfa08.png)

**Comment by urzds** [comment] 2015-11-27 17:30
[Enter steps to reproduce below:]

1. Start Atom with Nuclide
2. Observe this error message

I also tried `apm remove (apm ls | awk '/(nuclide-.*)/{gsub("@.*","");print$2}')` followed by `apm install nuclide-installer`, but that did not change anything.

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [nuclide-blame-provider-hg](https://github.com/facebooknuclideapm/nuclide-blame-provider-hg) package, v0.0.35


### Stack Trace

Failed to activate the nuclide-blame-provider-hg package

```
At Cannot find module 'nuclide-commons'

Error: Cannot find module 'nuclide-commons'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (${HOME}/.atom/packages/nuclide-blame-provider-hg/node_modules/nuclide-hg-git-bridge/lib/repositoryForPath.js:1:102)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.get [as repositoryForPath] (${HOME}/.atom/packages/nuclide-blame-provider-hg/node_modules/nuclide-hg-git-bridge/lib/main.js:20:14)
    at Object.<anonymous> (${HOME}/.atom/packages/nuclide-blame-provider-hg/lib/common.js:16:33)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (${HOME}/.atom/packages/nuclide-blame-provider-hg/lib/HgBlameProvider.js:40:15)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.provideHgBlameProvider (${HOME}/.atom/packages/nuclide-blame-provider-hg/lib/main.js:20:23)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:327:69)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:512:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:490:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:474:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:671:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:38:8)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:49:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:79:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.35
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-rust, v0.4.5
language-tmux, v0.4.0
latex, v0.28.2
latexer, v0.2.7
linter, v1.11.2
linter-csslint, v1.1.0
linter-gcc, v0.5.0
linter-htmlhint, v0.2.1
linter-lua, v1.0.0
linter-luacheck, v1.1.3
linter-rust, v0.2.10
linter-tidy, v1.0.1
minimap, v4.16.2
nuclide-arcanist, v0.0.35
nuclide-blame, v0.0.35
nuclide-blame-provider-hg, v0.0.35
nuclide-blame-ui, v0.0.35
nuclide-buck-files, v0.0.35
nuclide-busy-signal, v0.0.35
nuclide-clang-atom, v0.0.35
nuclide-code-format, v0.0.35
nuclide-code-highlight, v0.0.35
nuclide-debugger-atom, v0.0.35
nuclide-debugger-hhvm, v0.0.35
nuclide-debugger-lldb, v0.0.35
nuclide-diagnostics-store, v0.0.35
nuclide-diagnostics-ui, v0.0.35
nuclide-diff-view, v0.0.35
nuclide-file-tree, v0.0.35
nuclide-file-tree-deux, v0.0.32
nuclide-file-watcher, v0.0.35
nuclide-find-references, v0.0.35
nuclide-flow, v0.0.35
nuclide-fuzzy-filename-provider, v0.0.35
nuclide-hack, v0.0.35
nuclide-hack-symbol-provider, v0.0.35
nuclide-health, v0.0.35
nuclide-hg-repository, v0.0.35
nuclide-home, v0.0.35
nuclide-installer, v0.0.35
nuclide-language-hack, v0.0.35
nuclide-objc, v0.0.35
nuclide-ocaml, v0.0.35
nuclide-open-filenames-provider, v0.0.35
nuclide-quick-open, v0.0.35
nuclide-recent-files-provider, v0.0.35
nuclide-recent-files-service, v0.0.35
nuclide-remote-projects, v0.0.35
nuclide-test-runner, v0.0.35
nuclide-toolbar, v0.0.35
nuclide-type-hint, v0.0.35
nuclide-url-hyperclick, v0.0.35
pdf-view, v0.37.0
project-manager, v2.6.5
tool-bar, v0.1.9

# Dev
No dev packages
```

**Comment by mr-max** [comment] 2015-11-28 15:18
Same thing for me (Mac OS X 10.11.1)

**Comment by yilenpan** [comment] 2015-11-28 20:58
Same problem

**Comment by cedricwzy** [comment] 2015-11-29 02:00
same issue here

**Comment by phoenixlaef** [comment] 2015-11-29 10:18
I am having this issue on Windows 10 and Ubuntu 15.10... Was a clean install of Atom and installed all `nuclide-` packages.

**Comment by wwwtete** [comment] 2015-11-30 04:24
Same problem

**Comment by arunabha** [comment] 2015-11-30 05:16
I have the same problem.

**Comment by phoenixlaef** [comment] 2015-11-30 11:11
I have got this working without atom crashing in Windows 10 and Ubuntu 15.10:

1. I deleted all `nuclide-` folders in the `packages` folder which can be found in the `.atom` folder (Linux: `/home/username/.atom` Windows: `C:\Users\username\.atom`) I think that's right? I'm on my phone right now so sorry if it isn't :/
2. I installed `nuclide-commons` with `npm install nuclide-commons`
3. Installed `nuclide-installer` with `apm install nuclide-installer`
4. I then opened atom and the nuclide installer did it's thing installing other needed packages.

I'm not sure if that will help anyone but it worked for me.

**Comment by urzds** [comment] 2015-11-30 13:51
This indeed works around the issue.

1. I purged all Nuclide Atom modules `apm remove (apm ls | awk '/nuclide-/{gsub("@.*","");print$2}')`,
2. installed `nuclide-commons` to my home directory (`cd $HOME && npm install nuclide-commons`)
3. and then reinstalled `nuclide-installer`. 
4. I did not see the error message since.

**Comment by acid009** [comment] 2015-11-30 20:56
>> npm install nuclide-commons

It will be using default node.js installation not the internal atom's node.js ?
Shouldn't we change atom's node instead ?

**Comment by itsnotvalid** [comment] 2015-12-01 10:49
For me the basic workaround is to disable this package, since (luckily) I don't use hg for any of my major projects.

**Comment by flyingPastaMonster** [comment] 2015-12-04 08:38
Same problem here on Ubuntu 15.10 after a fresh installation I just installed the nuclide-installer package and got this error.

I guess I won't use nuclide than because I need mercurial.

**Comment by atkawa7** [comment] 2015-12-06 01:49
@urzds your command seems to not to work on ubuntu added $ before (

**Comment by plrthink** [comment] 2015-12-07 09:40
same problem here with atom 1.2.4

**Comment by urzds** [comment] 2015-12-07 10:02
@atkawa7 Thanks for the report. I'm using the [Fish shell](http://fishshell.com/), which has a slightly different syntax. I fixed the original comment to use Bash syntax.

**Comment by velocityboy** [comment] 2015-12-08 04:37
I see the same thing. Also, after getting to this point, Atom is unusable because its helper process is spinning at 100% CPU.

**Comment by sahas-** [comment] 2015-12-10 00:15
+1
Tried the workarounds suggested here, no luck.

<img width="444" alt="screen shot 2015-12-09 at 6 14 31 pm" src="https://cloud.githubusercontent.com/assets/10361685/11702975/cc1128c4-9ea0-11e5-97c0-0f90707dd6d3.png">

**Comment by bradleat** [comment] 2015-12-10 04:00
+1 Tried everything here, no luck.

**Comment by tdugger** [comment] 2015-12-12 00:23
Same problem with atom 1.3.1 on mac OS X 10.11.2.

**Comment by Kikobeats** [comment] 2015-12-12 20:00
some problem

**Comment by donald-jackson** [comment] 2015-12-13 21:35
I was also having this problem and took the following steps (on Mac)

1) Close Atom
2) cd ~/.atom/packages/nuclide-blame-provider-hg
3) npm install nuclide-commons
4) Start Atom, error should be gone.

**Comment by tszekely** [comment] 2015-12-14 11:55
The solution posted by @donald-jackson  worked for me, Windows 8.1

**Comment by mjvanleeuwen** [comment] 2015-12-14 15:56
Same problem with Atom 1.3.1 on Ubuntu 1510

Workaround I used was to reinstall Atom, install nuclide-installer, shutdown Atom, delete the .atom/packages/nuclide-blame-provider-hg directory, then restart Atom for the rest of the nuclide packages to be installed.

**Comment by Kikobeats** [comment] 2015-12-14 16:32
@donald-jackson so maybe the dependency is missing in the package.json of the folder?

**Comment by beevelop** [comment] 2015-12-14 21:15
@Kikobeats Yes, *nuclide-commons* seems not to be explicitly listed as npm dependency in *nuclide-blame-provider-hg*'s package.json. @donald-jackson's approach worked for me too on Windows 7.

**Comment by hackeram6** [comment] 2015-12-15 00:27
The problem is that the ~/.atom/packages/nuclide-blame-provider-hg/package.json installs nuclide-commons in the wrong path.

**"path": "node_modules/nuclide-analytics/node_modules/nuclide-commons/lib/main.js"**
should have been 
  **"path": "node_modules/nuclide-commons/lib/main.js"**

You could move nuclide-commons to the right path. @donald-jackson's approach works as well.

**Comment by ssorallen** [comment] 2015-12-17 00:16
nuclide-hg-git-bridge incorrectly lists its dependencies as "devDependencies" when they should be real "dependencies". After letting nuclide-installer do its work, nuclide-blame-provider-hg/node_modules/nuclide-hg-git-bridge/ does not have a node_modules because it lists no real dependencies.

**Comment by ryanpcmcquen** [comment] 2015-12-17 22:18
Affected by this as well.

**Comment by guangzhi405** [comment] 2015-12-18 02:02
@donald-jackson THx  It worked for me.

**Comment by itinance** [comment] 2015-12-24 10:14
thx @donald-jackson, it works for me

**Comment by bcalik** [comment] 2015-12-27 00:56
@donald-jackson's solution works, but it does not solve 100% cpu usage.

**Comment by jaredpalmer** [comment] 2015-12-27 19:58
+1

**Comment by Epotignano** [comment] 2016-01-05 21:27
same problem! +1!

**Comment by blablapolicja** [comment] 2016-01-09 22:38
+1

**Comment by king6cong** [comment] 2016-01-10 04:20
same +1

**Comment by G3z** [comment] 2016-01-13 13:54
+1

**Comment by nlitterat** [comment] 2016-01-14 12:27
+1 
I just want to say that it was my first try with Atom and I could not even find the commons package
Each install of the nuclide-installer took HOURS 
It create so deep nested directories that my poor window machine could not delete
it was hell
I really do not understand this

**Comment by viatsko** [comment] 2016-01-14 12:28
It's now should be fixed by http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/

**Comment by G3z** [comment] 2016-01-14 13:25
it is fixed! remove nuclide-installer !

**Comment by nmote** [comment] 2016-01-14 16:55
Yep, should be fixed by the unified package.

**Closed by nmote** 2016-01-14 16:55 UTC
