### ISSUE TITLE
Nuclide causes atom 1.3.1 to become unresponsive

### ISSUE THREAD

**Issue by AdamKyle** [facebook/nuclide#277] opened 2015-12-16 06:05 UTC
So I did:

```js
apm install nuclide-installer
```

And then opened atom, 45 minutes later all of nuclide finished installing. **45 minutes**. Any how, after that I closed atom, re opened it - minute later: 

```
The editor is not responding. Would you like to force close it or just keep waiting?
```

It does this all the time. Atom is now unusable.

- Mac Book pro 17 inch 2010 i7 dual core laptop.
- Also tried on my quad core i7 2012 mac mini

Ideas?

If Atom stays open too long even when it doesn't tell me its "unresponsive", it can make my system come straight to a crawl. I have no other "plugins" installed with atom.

**Comment by AdamKyle** [comment] 2015-12-16 18:56
**Update**

After removing all the nuclide packages atom become responsive, fast and usable again.

**Comment by ssorallen** [comment] 2015-12-16 23:50
We have some major redesigning of Nuclide going on right now that aims to address this issue in particular. We recognize this has made Nuclide unusable for you and many other open source users and will have are working on getting the new version out soon. You can read instructions on how to try it now (same as other Atom packages) in the [README](https://github.com/facebook/nuclide#nuclide).

Thanks for the issue; we are on it. I am going to close this as a duplicate of #232.

**Closed by ssorallen** 2015-12-16 23:50 UTC
