### ISSUE TITLE
Nuclide Debugger Causes React Native Application to Hang on Start

### ISSUE THREAD

**Issue by hborders** [facebook/nuclide#978] opened 2017-01-11 21:17 UTC
### Issue and Steps to Reproduce
1. Created a default react native application with `react-native init`
2. Ran `Nuclide React Native: Start Packager`
3. Ran `react-native run-ios` to start my app
4. Enabled remote JS debugging within the iOS simulator
5. Ran `Nuclide React Native: Start Debugging`
6. Reloaded my app in the iOS simulator with `cmd-r`.

Note that I set no breakpoints

### Expected Behavior
My app should start normally, the same as if I had not enabled debugging.

### Actual Behavior
My app doesn't start normally. I see only a white screen.

### Versions
* Atom: 1.13.0
* Nuclide: 0.197.0
* Client OS: Mac OS X 10.11.6
* Server OS (optional):

### Additional Details
└── nuclide@0.197.0

**Comment by kurtfunai** [comment] 2017-01-12 01:07
Having this exact same issue with:
- Atom: 1.13.0
- Nuclide: 0.197.0
- Client OS: Mac OS X 10.12.2

**Comment by jtokoph** [comment] 2017-01-20 03:57
I had this happen to me today. Interestingly, my app was working in the morning, and stopped working when I tried again in the evening.

It turns out that I had updated nodejs today to 7.4.0 from 7.2.1. After reverting to 7.2.1 the debugged application no longer hangs.

**Comment by johnislarry** [comment] 2017-01-23 21:44
Could be related to https://github.com/facebook/nuclide/issues/900.  If someone wants to build React Native from master (or wait until early Feb for the RC to be published and try that) and confirm that the issue still repros, that would be useful information.  The difference between these two issues could be explained by different versions of RN, or different versions of iOS.

**Comment by wellyshen** [comment] 2017-01-25 04:11
I have the same issue with :

Atom: 1.13.0
Nuclide: 0.201.0
Client OS: Mac OS X 10.12.2

**Comment by wellyshen** [comment] 2017-02-04 08:36
I have updated my RN to 0.42.0-rc.1, but this issue still exist, I show the screenshot as below : 
<img width="1280" alt="2017-02-04 4 33 51" src="https://cloud.githubusercontent.com/assets/21308003/22617126/dd34fdd4-eaf7-11e6-85b3-695d0a8bdedc.png">

Atom: 1.13.1 x64
Nuclide: 0.202.0
Client OS: Mac OS Sierra 10.12.3
RN: 0.42.0-rc.1
Node: 7.4.0

**Comment by wellyshen** [comment] 2017-02-06 09:14
@johnislarry I update my node from 7.4.0 to 7.5.0, then this issue was be fixed, actually I don't why but congrats for myself XD

**Comment by johnislarry** [comment] 2017-02-07 21:24
Closing as fixed.  If you still have issues please file a new task and include detailed repro steps, along with the versions of RN, node, OS, etc that you are using.  Thank you!

**Closed by johnislarry** 2017-02-07 21:24 UTC

**Comment by ikzjfr0** [comment] 2017-02-27 01:21
node version is the root cause. same situation as @wellyshen. it's ok after upgrading node from 7.4.0 to 7.5.0,
