### ISSUE TITLE
Color doesn't change on tree-view even after modification of file under source control.

### ISSUE THREAD

**Issue by Kaijun** [facebook/nuclide#410] opened 2016-03-15 22:50 UTC
### Issue and Steps to Reproduce
Color doesn't change on tree-view even after modification of file under source control.
Reinstalled Atom and Nuclide doesn't help!
![screen shot 2016-03-15 at 23 45 59](https://cloud.githubusercontent.com/assets/1693027/13796695/760a799e-eb08-11e5-8134-c25b0ca1fa96.png)

### Expected Behavior
The color of the file name should turn yellow

### Actual Behavior
The color of the file name doesn't turn yellow

### Versions
* Atom: 1.5.4
* Nuclide: 0.124.0
* Client OS: OSX 10.10 
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by lightning18** [comment] 2016-03-16 01:20
Duplicate of #260

**Comment by ssorallen** [comment] 2016-03-16 17:40
Thanks for the report. The Nuclide file-tree has limited Git support at the moment. Closing this as a duplicate of #260 as @lightning18 mentioned.

**Closed by ssorallen** 2016-03-16 17:40 UTC
