### ISSUE TITLE
High CPU when opening ATOM

### ISSUE THREAD

**Issue by ChristianGrech** [facebook/nuclide#103] opened 2015-06-25 16:30 UTC
Been using atom on Windows 8 for about a 2 months with no problems. However, after installing nuclide-installer I've been noticing that when opening atom my cpu percentage increases.

I have disabled nuclide-installer and the problem didn't occur, but when re-enabling it the cpu increases again.

I have included a snippet of the task manager as the problem looks to be with Evented I/O V8 engine for node.js. 

I have also noted that the installer have only installed 2 other packages; nuclide-language-hack and nuclide-type-hint

![image](https://cloud.githubusercontent.com/assets/4950218/8359575/81ac0c84-1b67-11e5-8176-2c212f3f1337.png)

**Comment by SiebelsTim** [comment] 2015-06-25 18:25
The installer is extremely silent I had to experience today. I think in your case it is still installing all the other packages. Either install them manually (apm install nuclide-...) or wait some time. I have 13 packages related to nuclide installed currently. I guess that's all of them.

**Comment by ChristianGrech** [comment] 2015-06-25 20:12
I left it running for 15 minutes each time but the cpu was still at a high percentage each time.

**Comment by bwhitty** [comment] 2015-06-25 20:19
I experienced the same thing today. With Atom 1.0, I installed the nuclide-installer and then each time I tried to install an indiviual Nuclide package, my CPU would peg with 1 or 2 Node processes at 100% CPU. Though I cannot reproduce this once those processes had finished (note they ran for 20+ minutes at 100% CPU). Running OSX 10.10.3.

**Comment by danneu** [comment] 2015-06-26 11:21
I experienced this too. Made Atom unusable and prevented the "Packages" tab from ever loading.

I uninstalled each nuclide package one by one (`apm uninstall nuclide-*`) and seem to have narrowed it down to `nuclide-file-tree`.

**Comment by ChristianGrech** [comment] 2015-06-26 11:41
I left it running for over an hour until it stopped on its own. However, still no more packages were installed. Is there a list of all the packages so I can install it manually.

I have also updated the package to 0.0.22 but still got the same issue.

**Comment by ssorallen** [comment] 2015-06-26 19:51
I'm going to close this in favor of #84 so we can keep the discussion and investigation in one place. Let me know if you feel they are separate issues.

**Closed by ssorallen** 2015-06-26 19:51 UTC
