### ISSUE TITLE
Failed to load the nuclide-blame-ui package

### ISSUE THREAD

**Issue by niieani** [facebook/nuclide#494] opened 2016-05-12 13:20 UTC
### Issue and Steps to Reproduce
Installing nuclide package or opening new Atom window

### Expected Behavior
No error

### Actual Behavior
2 errors appear:

```
Error compiling Less stylesheet: /Users/nixin/.atom/packages/nuclide/pkg/nuclide-blame-ui/styles/gutter.atom-text-editor.less
Line number: 24
.loading-spinner-tiny is undefined
```

```
Failed to load the nuclide-blame-ui package
.loading-spinner-tiny is undefined in /Users/nixin/.atom/packages/nuclide/pkg/nuclide-blame-ui/styles/gutter.atom-text-editor.less:24:2
Hide Stack Trace
LessError: .loading-spinner-tiny is undefined
  at /Users/nixin/.atom/packages/nuclide/pkg/nuclide-blame-ui/styles/gutter.atom-text-editor.less:24:2
```

### Versions
* Atom: 1.7.3
* Nuclide: 0.135.0
* Client OS: OS X 10.11.4 (15E65)
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

```
Community Packages (43) /Users/nixin/.atom/packages
├── atom-beautify@0.29.2
├── atom-typescript@8.9.1
├── autoclose-html@0.23.0
├── autocomplete-emojis@2.3.0
├── autocomplete-html-entities@0.1.0
├── autocomplete-modules@1.4.1
├── autocomplete-paths@1.0.2
├── blackspace@1.1.0
├── build@0.59.0
├── clang-format@1.25.0
├── devdocs@0.2.1
├── esformatter@1.25.0
├── gist-it@0.9.1
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── icon-fonts@2.4.1
├── imdone-atom@1.3.29
├── isotope-ui@2.7.1
├── language-babel@2.17.2
├── language-docker@1.1.6
├── language-ini@1.16.0
├── language-javascript-semantic@0.2.1
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── linter@1.11.4
├── linter-shellcheck@1.1.0
├── linter-tslint@0.9.1
├── material-syntax@0.5.0
├── minimap@4.21.0
├── nuclide@0.135.0
├── pigments@0.26.0
├── react@0.15.0
├── remote-sync@4.0.1
├── semantic-ui@1.0.7
├── seti-ui@1.1.2
├── sort-lines@0.14.0
├── sync-settings@0.7.2
├── terminal-plus@0.14.5
├── toggle-quotes@1.0.0
├── tool-bar@0.4.0
├── unity-dark-ui@2.0.9
├── unsaved-changes@0.1.0
└── zentabs@0.8.7
```

**Comment by ssorallen** [comment] 2016-05-12 17:09
Duplicate of #484.

The fix is in master and will be out shortly with the next release.

**Closed by ssorallen** 2016-05-12 17:09 UTC

**Comment by ssorallen** [comment] 2016-05-12 17:31
v0.136.0 has been released, and I verified the exception no longer happens with [seti-ui](https://atom.io/themes/seti-ui). Please comment again if you're still seeing this after upgrading.
