### ISSUE TITLE
Failed to activate the nuclide-debugger-atom package

### ISSUE THREAD

**Issue by nevi-me** [facebook/nuclide#250] opened 2015-11-18 10:05 UTC
[Enter steps to reproduce below:]

1. Open Atom
2. Get error relating to nuclide

**Atom Version**: 1.2.1
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [nuclide-debugger-atom](https://github.com/facebooknuclideapm/nuclide-debugger-atom) package, v0.0.32

### Stack Trace

Failed to activate the nuclide-debugger-atom package

```
At deprecationSite.getFileName is not a function

TypeError: deprecationSite.getFileName is not a function
    at Object.global.__grim__.deprecate (%USERFOLDER%\AppData\Local\atom\app-1.2.1\resources\app.asar\node_modules\grim\lib\grim.js:56:36)
    at Object.defineProperty.get [as TextEditor] (%USERFOLDER%\AppData\Local\atom\app-1.2.1\resources\app.asar\exports\atom.js:38:14)
    at Object.<anonymous> (%USERFOLDER%\.atom\packages\nuclide-debugger-atom\lib\BreakpointManager.js:17:26)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (%USERFOLDER%\AppData\Local\atom\app-1.2.1\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (%USERFOLDER%\.atom\packages\nuclide-debugger-atom\lib\DebuggerModel.js:18:25)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.4
atom-material-ui, v0.7.1
hex, v0.6.2
hyperclick, v0.0.32
language-r, v0.4.0
language-sas, v0.2.4
language-scala, v1.1.4
nuclide-arcanist, vundefined
nuclide-blame, v0.0.32
nuclide-blame-provider-hg, v0.0.32
nuclide-blame-ui, v0.0.32
nuclide-buck-files, v0.0.32
nuclide-clang-atom, v0.0.32
nuclide-code-format, v0.0.32
nuclide-debugger-atom, v0.0.32
nuclide-debugger-hhvm, v0.0.32
nuclide-debugger-lldb, v0.0.32
nuclide-diagnostics-store, v0.0.32
nuclide-diagnostics-ui, v0.0.32
nuclide-diff-view, v0.0.32
nuclide-file-tree, v0.0.32
nuclide-file-tree-deux, v0.0.32
nuclide-file-watcher, v0.0.32
nuclide-find-references, v0.0.32
nuclide-flow, v0.0.32
nuclide-fuzzy-filename-provider, v0.0.32
nuclide-hack, v0.0.32
nuclide-hack-symbol-provider, v0.0.32
nuclide-hg-repository, v0.0.32
nuclide-installer, v0.0.32
nuclide-language-hack, v0.0.32
nuclide-objc, v0.0.32
nuclide-ocaml, v0.0.32
nuclide-open-filenames-provider, v0.0.32
nuclide-quick-open, v0.0.32
nuclide-remote-projects, v0.0.32
nuclide-type-hint, v0.0.32
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by atom992** [comment] 2015-11-18 11:18
I have the same issue on MAC OS X 10.10.5

**Comment by nmote** [comment] 2015-11-18 14:30
Duplicate of #246

**Closed by nmote** 2015-11-18 14:30 UTC
