### ISSUE TITLE
nuclide-quick-open never finds files

### ISSUE THREAD

**Issue by ev-tt** [facebook/nuclide#129] opened 2015-07-05 20:02 UTC
![screenshot_2015-07-05_16_01_10](https://cloud.githubusercontent.com/assets/11943109/8513206/50a0f36e-232f-11e5-8b6c-84b29ae0a086.png)

Typing in name of the files, if it is open file , it is ok, as you can see it on the screenshoot.
Otherwise it will stay in this state, showing loading for two project folders and never return anything.
I have two project folders, both of them are ionic ( cordova) projects.

**Comment by simonwelsh** [comment] 2015-07-06 01:26
Duplicate of #83.

**Comment by jssln** [comment] 2015-07-06 15:39
Let's close this in favor of discussion on #83.

**Closed by jssln** 2015-07-06 15:39 UTC
