### ISSUE TITLE
Uncaught AssertionError: false == true

### ISSUE THREAD

**Issue by ryu-monk** [facebook/nuclide#513] opened 2016-05-24 19:50 UTC
[Enter steps to reproduce below:]

1. Start nuclide server in ubuntu: nuclide-start-server
2. Connect to remote server from OSX to Ubuntu 14

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.138.0

### Stack Trace

Uncaught AssertionError: false == true

```
At assert.js:89

AssertionError: false == true
  at ClientComponent._handleMessage (/Users/cm4o/.atom/packages/nuclide/pkg/nuclide-rpc/lib/ClientComponent.js:327:43)
  at EventEmitter.<anonymous> (/Users/cm4o/.atom/packages/nuclide/pkg/nuclide-rpc/lib/ClientComponent.js:90:20)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)
  at /Users/cm4o/.atom/packages/nuclide/pkg/nuclide-server/lib/NuclideSocket.js:115:22
  at Function.module.exports.Emitter.simpleDispatch (/Users/cm4o/.atom/packages/nuclide/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Users/cm4o/.atom/packages/nuclide/node_modules/event-kit/lib/emitter.js:125:28)
  at QueuedTransport._onMessage (/Users/cm4o/.atom/packages/nuclide/pkg/nuclide-server/lib/QueuedTransport.js:110:21)
  at /Users/cm4o/.atom/packages/nuclide/pkg/nuclide-server/lib/QueuedTransport.js:92:22
  at Function.module.exports.Emitter.simpleDispatch (/Users/cm4o/.atom/packages/nuclide/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Users/cm4o/.atom/packages/nuclide/node_modules/event-kit/lib/emitter.js:125:28)
  at WebSocketTransport._onSocketMessage (/Users/cm4o/.atom/packages/nuclide/pkg/nuclide-server/lib/WebSocketTransport.js:91:21)
  at WebSocket.<anonymous> (/Users/cm4o/.atom/packages/nuclide/pkg/nuclide-server/lib/WebSocketTransport.js:59:20)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:172:7)
  at Receiver.ontext (/Users/cm4o/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:816:10)
  at /Users/cm4o/.atom/packages/nuclide/node_modules/ws/lib/Receiver.js:477:18
  at /Users/cm4o/.atom/packages/nuclide/node_modules/ws/lib/Receiver.js:361:7
  at /Users/cm4o/.atom/packages/nuclide/node_modules/ws/lib/PerMessageDeflate.js:247:5
  at afterWrite (_stream_writable.js:346:3)
  at onwrite (_stream_writable.js:337:7)
  at WritableState.onwrite (_stream_writable.js:89:5)
  at afterTransform (_stream_transform.js:79:5)
  at TransformState.afterTransform (_stream_transform.js:54:12)
  at Zlib.callback (zlib.js:613:5)

```

### Commands

```
 23x -0:52.9.0 core:backspace (atom-text-editor.atom-text-editor-unstyled.mini.is-focused)
     -0:39.7.0 core:confirm (atom-text-editor.atom-text-editor-unstyled.mini.is-focused)
     -0:29 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:07.4.0 core:copy (atom-text-editor.atom-text-editor-unstyled.mini.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "lastConnectionDetails": {
      "lastOfficialRemoteServerCommand": "nuclide-start-server",
      "updatedConfig": {
        "authMethod": "PASSWORD",
        "cwd": "/home/cm4",
        "displayTitle": "(default)",
        "host": "10.12.2.148",
        "password": "",
        "pathToPrivateKey": "/Users/cm4o/.ssh/id_rsa",
        "remoteServerCommand": "nuclide-start-server",
        "sshPort": "22",
        "username": "cm4"
      }
    },
    "nuclide-home": {}
  }
}
```

### Installed Packages

```coffee
# User
nuclide, v0.138.0
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by shushz** [comment] 2016-05-25 05:32
It seems that the exception is thrown from a class that no longer exists in Nuclide as of version v0.137
I suspect it might be an issue caused by Atom cache. Could you, please, try restarting Atom and see whether the problem is still reproducible?

**Comment by nmote** [comment] 2016-05-26 22:41
Please reopen if this doesn't work.

**Comment by joepsz** [comment] 2016-06-23 15:04
I'm getting the same error when I click 'uncommited changes' in the side tab in Source Control mode. Running Atom 1.8.0 and Nuclide 0.146. 

Stack:

```
/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14
Hide Stack Trace
AssertionError: false == true
  at RepositorySectionComponent._handleUncommittedChangesClick (/Users/joep/.atom/packages/nuclide/pkg/nuclide-source-control-side-bar/lib/RepositorySectionComponent.js:81:43)
  at Object.r (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:21971)
  at a (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:23434)
  at Object.s [as executeDispatchesInOrder] (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:23649)
  at p (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:20137)
  at f (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:20263)
  at Array.forEach (native)
  at r (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:12963)
  at Object.h.processEventQueue (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:21217)
  at r (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:22235)
  at Object.i.handleTopLevel [as _handleTopLevel] (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:22336)
  at i (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:22783)
  at r.o.perform (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at Object.d.batchedUpdates (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:17100)
  at Object.i [as batchedUpdates] (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:15:16775)
  at v.dispatchEvent (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:23665)
```

**Comment by nmote** [comment] 2016-06-23 16:40
@ssorallen looks like a problem with the source control sidebar

**Comment by AWTrost** [comment] 2016-06-24 14:07
Still an issue, reproducible 100% of the time after nuclide/atom restart.  I'll just disable the sidebar, but would be nice if it worked.  Although i'm not using hg (not sure what other VCS are supported).

**Comment by jamesgpearce** [comment] 2016-06-26 03:24
@ssorallen, 100% repro when clicking 'Uncommitted Changes' in sidebar on a git repo...

**Comment by jamesgpearce** [comment] 2016-06-26 03:24
(appreciate this may be different cause to original issue which predated bookmark switcher)

**Comment by kevinfrei** [comment] 2016-06-30 22:02
It works for me with Hg, and fails with Git. I'd really love it if all the marvelous Hg goodness was extended to work with Git :)

**Comment by victoriafrench** [comment] 2016-07-01 04:19
same exact issue as @joepsz on OSX

**Comment by rricard** [comment] 2016-07-01 09:32
Definitely triggered while using git on  the source control side bar. Here is the stacktrace there:

```
AssertionError: false == true
  at RepositorySectionComponent._handleUncommittedChangesClick (/Users/rricard/.atom/packages/nuclide/pkg/nuclide-source-control-side-bar/lib/RepositorySectionComponent.js:83:43)
  at Object.r (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:21971)
  at a (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:23434)
  at Object.s [as executeDispatchesInOrder] (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:23649)
  at p (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:20137)
  at f (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:20263)
  at Array.forEach (native)
  at r (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:12963)
  at Object.h.processEventQueue (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:21217)
  at r (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:22235)
  at Object.i.handleTopLevel [as _handleTopLevel] (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:22336)
  at i (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:22783)
  at r.o.perform (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at Object.d.batchedUpdates (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:17100)
  at Object.i [as batchedUpdates] (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:15:16775)
  at v.dispatchEvent (/Users/rricard/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:23665)
```

**Comment by ssorallen** [comment] 2016-07-01 16:57
Thanks for the report. I will put up a fix for this.

**Comment by ssorallen** [comment] 2016-07-01 17:19
The stack in the comments about the source control side bar is not the same cause as the original issue. I opened #569 to track the side bar issue and am closing this one as can-not-repro given the original comments.

**Closed by ssorallen** 2016-07-01 17:19 UTC
