### ISSUE TITLE
Uncaught Error: Undefined screen line when clipping screen position

### ISSUE THREAD

**Issue by eklavya** [facebook/nuclide#292] opened 2015-12-26 16:45 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Uncaught Error: Undefined screen line when clipping screen position

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:886

Error: Undefined screen line when clipping screen position
  at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:874:15)
  at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:826:20)
  at TextEditor.module.exports.TextEditor.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1241:33)
  at HyperclickForTextEditor._getMousePositionAsBufferPosition (/Users/eklavya/Documents/nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:265:31)
  at HyperclickForTextEditor._isMouseAtLastWordRange (/Users/eklavya/Documents/nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:285:43)
  at HyperclickForTextEditor._onMouseMove (/Users/eklavya/Documents/nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:146:16)

```

### Commands

```
  3x -9:55.8.0 core:move-left (atom-text-editor.editor.is-focused)
 20x -9:54.8.0 core:select-right (atom-text-editor.editor.is-focused)
  7x -9:47.4.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -9:46.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -9:44.4.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -9:43.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -9:41.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  4x -9:40.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:37.8.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -9:29.4.0 core:save (atom-text-editor.editor.is-focused)
     -4:44.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:18.3.0 git-plus:commit (atom-text-editor.editor.is-focused)
     -1:59 git-plus:add (atom-text-editor.editor.is-focused)
  2x -1:53.9.0 nuclide-file-tree:toggle (atom-text-editor.editor.is-focused)
     -1:28.9.0 git-plus:checkout (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.7.0 git-plus:commit (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": false,
    "disabledPackages": [
      "tree-view",
      "linter"
    ]
  },
  "nuclide": {
    "nuclide-arcanist": {},
    "nuclide-buck-files": {},
    "nuclide-debugger-hhvm": {},
    "nuclide-flow": {
      "diagnosticsOnFly": true,
      "enableStructuredTypeHints": true,
      "pathToFlow": "/usr/local/bin/flow"
    },
    "nuclide-format-js": {
      "reprint": true
    },
    "nuclide-health": {
      "showMemory": true,
      "showCpu": true,
      "showHeap": true,
      "viewTimeout": 5
    },
    "nuclide-ocaml": {},
    "nuclide-diagnostics-ui": {
      "enableAutofix": true
    },
    "nuclide-file-tree": {
      "revealFileOnSwitch": true
    }
  }
}
```

### Installed Packages

```coffee
# User
git-plus, v5.8.2
nuclide, v0.0.0

# Dev
No dev packages
```

**Comment by mostafaeweda** [comment] 2016-01-14 23:35
Could you verify if our latest UP release fixes this, http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/ - otherwise, feel free to reopen.

**Comment by ssorallen** [comment] 2016-01-15 00:14
Check out the OP's installed packages list:

```
# User
git-plus, v5.8.2
nuclide, v0.0.0

# Dev
No dev packages
```

This is the UP.

**Comment by ssorallen** [comment] 2016-01-15 00:15
Although it was from source since the version is v0.0.0. Yeah, makes sense to close it. @eklavya, can you verify if this still happens with the released version of 'nuclide': v0.111.0?

**Comment by eklavya** [comment] 2016-01-15 06:00
I have already forgotten what was causing it. But the things I tried didn't result in this error anymore, so maybe it's fixed.

**Comment by samuelcole** [comment] 2016-01-15 19:22
I just got this error, while closing a tab:

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.111.0


### Stack Trace

Uncaught Error: Undefined screen line when clipping screen position

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:886

Error: Undefined screen line when clipping screen position
    at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:874:15)
    at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:826:20)
    at TextEditor.module.exports.TextEditor.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1255:33)
    at HyperclickForTextEditor._getMousePositionAsBufferPosition (/Users/sam/.atom/packages/nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:264:31)
    at HyperclickForTextEditor._onMouseMove (/Users/sam/.atom/packages/nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:149:95)
```

### Commands

```
     -0:37.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:36.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:34.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:33.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:33.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:07.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:07.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:07.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:07.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:07.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:07.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:07.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:02.3.0 core:close (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "nuclide-arcanist": {},
    "nuclide-buck-files": {},
    "nuclide-debugger-hhvm": {},
    "nuclide-flow": {},
    "nuclide-format-js": {},
    "nuclide-health": {},
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-ocaml": {}
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.11.3
linter-eslint, v5.2.7
nuclide, v0.111.0
react, v0.14.0
react-snippets, v0.3.0

# Dev
No dev packages
```

**Comment by mostafaeweda** [comment] 2016-01-15 21:22
I can't seem to be able to reproduce that, any repro steps I can try?

**Comment by samuelcole** [comment] 2016-01-15 21:30
I have no idea, it just happened to me randomly.

I installed everything today, so it should all be up to date.

**Comment by jamesgpearce** [comment] 2016-01-27 23:00
Just got this after closing a bunch of tabs quickly and resizing the window at approximately the same time

**Comment by samwgoldman** [comment] 2016-02-25 22:42
Got this as well, also closing tabs quickly.

Stack trace (slightly sanitized)
```
/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:886
Hide Stack Trace
Error: Undefined screen line when clipping screen position
  at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:874:15)
  at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:826:20)
  at TextEditor.module.exports.TextEditor.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1283:33)
  at HyperclickForTextEditor._getMousePositionAsBufferPosition (pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:266:31)
  at HyperclickForTextEditor._isMouseAtLastWordRange (pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:286:43)
  at HyperclickForTextEditor._onMouseMove (pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:147:16)
```

**Comment by nmote** [comment] 2016-03-01 21:25
I just got this too. I closed the settings panel (with the nuclide package settings showing) using cmd+w. I didn't do any resizing, although I do have a split pane with outline view on the right.

```                                                                              
Error: Undefined screen line when clipping screen position                       
  at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:874:15)
  at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:826:20)
  at TextEditor.module.exports.TextEditor.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1283:33)
  at HyperclickForTextEditor._getMousePositionAsBufferPosition (.../Nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:266:31)
  at HyperclickForTextEditor._isMouseAtLastWordRange (.../Nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:286:43)
  at HyperclickForTextEditor._onMouseMove (.../Nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:147:16)
```

**Closed** 2016-03-02 09:20 UTC
