### ISSUE TITLE
nuclide  of  debugger Controls  can’t work

### ISSUE THREAD

**Issue by q351941406** [facebook/nuclide#859] opened 2016-11-03 03:54 UTC
### Issue and Steps to Reproduce
nuclide of debugger Controls can’t work，Can work under node version 4.4.0

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom:1.11.2
* Nuclide:0.178.0
* node:7.0.0
* Client OS:
* Server OS (optional):

Details
 `[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.178.0

### Stack Trace

Uncaught TypeError: Cannot read property 'ref' of undefined

```
At /Users/ggg/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/InjectorClient.js:111

TypeError: Cannot read property 'ref' of undefined
  at InjectorClient.<anonymous> (/Users/ggg/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/InjectorClient.js:111:22)
  at /Users/ggg/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/DebuggerClient.js:121:7
  at Object.create.processResponse.value (/Users/ggg/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/callback.js:23:20)
  at Debugger._processResponse (/Users/ggg/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/VendorLib/node-inspector/lib/debugger.js:95:21)
  at Protocol.execute (_debugger.js:120:14)
  at emitOne (events.js:90:13)
  at Socket.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at TCP.onread (net.js:531:20)

```

### Commands

```
  3x -7:50.4.0 nuclide-outline-view:toggle (atom-text-editor.editor)
     -7:39.9.0 nuclide-debugger:show (atom-text-editor.editor.is-focused)
     -0:00.1.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "telemetryConsent": "limited"
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-flow": {},
    "nuclide-working-sets": {
      "workingSets": [
        {
          "name": "得到的",
          "active": true,
          "uris": [
            "/Users/mac/Desktop/object/ReactNative/aaaaaaa"
          ]
        },
        {
          "name": "na",
          "active": true,
          "uris": [
            "/Users/mac/Desktop/object/ReactNative/aaaaaaa"
          ]
        }
      ]
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-react-native-autocomplete, v0.0.27 (active)
atom-react-native-css, v1.1.3 (active)
autocomplete-js-import, v1.2.1 (active)
color-picker, v2.2.2 (active)
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.11.2 (active)
language-babel, v2.46.0 (active)
language-ini, v1.16.0 (active)
language-javascript-jsx, v0.3.7 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.4.0 (active)
language-thrift, v1.0.2 (active)
merge-conflicts, v1.4.4 (active)
nuclide, v0.178.0 (active)
nuclide-format-js, v0.0.36 (inactive)
pigments, v0.37.0 (active)
simplified-chinese-menu, v3.5.0 (active)
sort-lines, v0.14.0 (inactive)
sync-settings, v0.7.2 (active)
sync-settings, v0.7.2 (active)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

`

**Comment by jgebhardt** [comment] 2016-11-03 23:40
@q351941406 Please help us debug this by specifying all of the information requested in the issue template:

- [ ] Expected Behavior
- [ ] Actual Behavior
- [ ] Detailed steps to reproduce the problem
- the output of `node -v` on your machine (you mentioned two conflicting versions, `7.0.0` and `4.4.0`, in your issue)

Thanks!

**Comment by jgebhardt** [comment] 2017-01-11 20:55
Closing this since it's been 2 months. Please report back with repro steps if you are still experiencing this issue.

**Closed by jgebhardt** 2017-01-11 20:55 UTC
