### ISSUE TITLE
Failed to activate the nuclide-file-tree package

### ISSUE THREAD

**Issue by dimonge** [facebook/nuclide#365] opened 2016-02-16 12:09 UTC
I got the error message after install the nuclide package

ERROR
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [nuclide-file-tree](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Failed to activate the nuclide-file-tree package

```
At Tried to unload active package 'tree-view'

Error: Tried to unload active package 'tree-view'
    at PackageManager.module.exports.PackageManager.unloadPackage (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package-manager.js:468:15)
    at Object.activate (C:\Users\peter.shodeinde\.atom\packages\nuclide\pkg\nuclide\file-tree\lib\main.js:166:21)
    at Package.module.exports.Package.activateNow (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:181:20)
    at C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:155:32
    at Package.module.exports.Package.measure (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:92:15)
    at C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:148:26
    at Package.module.exports.Package.activate (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package-manager.js:526:21)
    at C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package-manager.js:502:19)
    at Object.activate (C:\Users\peter.shodeinde\.atom\packages\nuclide\lib\main.js:215:31)
    at Package.module.exports.Package.activateNow (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:181:20)
    at C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:155:32
    at Package.module.exports.Package.measure (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:92:15)
    at C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:148:26
    at Package.module.exports.Package.activate (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package-manager.js:526:21)
    at C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
    at exit (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\peter.shodeinde\AppData\Local\atom\app-1.5.3\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
nuclide, v0.116.0

# Dev
No dev packages
```

**Comment by ssorallen** [comment] 2016-02-16 18:16
Closing as a duplicate of #354. The fix will be in the next release, v0.117.0.

**Closed by ssorallen** 2016-02-16 18:16 UTC
