### ISSUE TITLE
Uncaught Error: Diff view only supports `Mercurial` repositories, but found `git` at path: `/home...

### ISSUE THREAD

**Issue by bunster** [facebook/nuclide#458] opened 2016-04-15 07:33 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Ubuntu 15.10
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.130.0

### Stack Trace

Uncaught Error: Diff view only supports `Mercurial` repositories, but found `git` at path: `/home/boonie/Projects/wasp`

```
At /home/boonie/.atom/packages/nuclide/node_modules/react/lib/ReactErrorUtils.js:53

Error: Diff view only supports `Mercurial` repositories, but found `git` at path: `/home/boonie/Projects/wasp`
  at hgRepositoryForPath (/home/boonie/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:134:11)
  at DiffViewModel._getRepositoryStackForPath (/home/boonie/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:636:26)
  at DiffViewModel._findFilePathToDiffInDirectory (/home/boonie/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:430:34)
  at DiffViewModel.diffEntity (/home/boonie/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:454:25)
  at activateDiffPath (/home/boonie/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:125:19)
  at createView (/home/boonie/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:77:3)
  at /home/boonie/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:222:16
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:489:22)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:424:19)
  at atom-workspace.diffActiveTextEditor (/home/boonie/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:171:20)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
  at React.createElement.React.createElement.React.createElement.onClick (/home/boonie/.atom/packages/nuclide/pkg/nuclide-home/lib/HomeFeatureComponent.js:50:38)
  at Object.invokeGuardedCallback (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/ReactErrorUtils.js:27:12)
  at executeDispatch (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:79:21)
  at Object.executeDispatchesInOrder (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:102:5)
  at executeDispatchesAndRelease (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:43:22)
  at executeDispatchesAndReleaseTopLevel (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:54:10)
  at Array.forEach (native)
  at forEachAccumulated (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/forEachAccumulated.js:23:9)
  at Object.EventPluginHub.processEventQueue (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:259:7)
  at runEventQueueInBatch (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:34:5)
  at handleTopLevelWithoutPath (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:93:24)
  at handleTopLevelImpl (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:73:3)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
  at Object.batchedUpdates (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:94:20)
  at ReactEventListener.dispatchEvent (/home/boonie/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:204:20)

```

### Commands

```
     -1:32.3.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:54.9.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:38.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 nuclide-diff-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-genesis-syntax.theme-genesis-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "themes": [
      "genesis-ui",
      "genesis-syntax"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true
  }
}
```

### Installed Packages

```coffee
# User
genesis-syntax, v1.0.7
genesis-ui, v0.4.0
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.17.2
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
nuclide, v0.130.0
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by zertosh** [comment] 2016-04-15 17:27
cc: @mostafaeweda

**Comment by mostafaeweda** [comment] 2016-04-16 02:55
As the error message explains, currently, the `Diff View` supports `Mercurial` repositories only, not `Git` at the moment.

**Comment by mostafaeweda** [comment] 2016-04-16 02:56
Duplicate of #436

**Closed by mostafaeweda** 2016-04-16 02:56 UTC
