### ISSUE TITLE
Wrong files indentation on file-tree

### ISSUE THREAD

**Issue by gcesarmza** [facebook/nuclide#1466] opened 2018-02-15 13:51 UTC
### Issue and Steps to Reproduce
The file tree view is showing a wrong indentation when showing files

### Expected Behavior
Files should be shown "inside" (indented) their respective containing folder

### Actual Behavior
Files are shown at the same level as their containing folder

### Versions
* Atom: 1.2.4
* Nuclide: 0.283.0
* Client OS: macOS Sierra 10.12.6

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (23)
├── MagicPython@1.0.12
├── file-icons@2.1.16
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── language-babel@2.83.4
├── language-graphql@0.9.0
├── language-haskell@1.17.3
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.1
├── merge-conflicts@1.4.5
├── nuclide@0.283.0
├── nuclide-format-js@0.0.44
├── prettier-atom@0.51.0
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.6

**Comment by pelmers** [comment] 2018-02-15 17:57
duplicate of #1459 , and I believe that 3704e5b1bb409f120e241b74272e2f6472e808a2 fixes it

**Closed by pelmers** 2018-02-15 17:57 UTC
